/******************************************************
 * Discussion Forge
 *
 * Generic conversation deck generation application.
 *
 * This module owns application configuration, catalog
 * loading, deck generation, rendering, user interaction,
 * manifest creation, and startup.
 ******************************************************/

/* =========================================================
 * Imports
 * ========================================================= */

import {
  bytesToHex,
  chunkArray,
  compareSemver,
  encodeBase32,
  randomCode,
  seededShuffle,
  sha256Bytes,
} from "./utils.js";

import { getTheme, themes } from "../themes/index.js";
import { validateCardPackManifest } from "./validators/card-pack-validator.js";
import { validateCard } from "./validators/card-validator.js";
import { validateCategory } from "./validators/category-validator.js";
import { validateEdition } from "./validators/edition-validator.js";
import { validateCatalogIntegrity } from "./validators/catalog-integrity-validator.js";
import { validateThemeDefinition } from "./validators/theme-validator.js";

/* =========================================================
 * Version and deck-identity contracts
 * ========================================================= */

/*
 * Increment this only when the canonical deck-identity
 * schema or fingerprint algorithm changes.
 *
 * Changing this value indicates that deterministic deck
 * identities generated by previous schema versions are not
 * directly comparable.
 */
const DECK_IDENTITY_SCHEMA_VERSION = 2;

/*
 * Discussion Forge application version recorded in
 * generated deck manifests and compatibility metadata.
 */
const GENERATOR_VERSION = "0.4.0";

/*
 * Number of Base32 characters exposed as the human-readable
 * deterministic Deck ID.
 */
const HUMAN_DECK_ID_LENGTH = 10;

/* =========================================================
 * Application identity
 * ========================================================= */

/*
 * Stable identity for the Discussion Forge application.
 *
 * Conversation content, branding, and card-back text belong
 * to installed card packs rather than to the application
 * itself.
 */
const APPLICATION = Object.freeze({
  id: "discussion-forge",
  displayName: "Discussion Forge",

  version: GENERATOR_VERSION,
});

/* =========================================================
 * Theme defaults
 * ========================================================= */

/*
 * Trail Blue is the canonical fallback theme.
 */
const DEFAULT_THEME_ID = "trail-blue";

/*
 * DOM ID used for the dynamically loaded theme stylesheet.
 */
const THEME_STYLESHEET_ID = "active-theme-stylesheet";

/* =========================================================
 * Runtime defaults
 * ========================================================= */

/*
 * Number of characters generated by the Random Seed button.
 *
 * This controls the application's generated seed format,
 * not the maximum seed length accepted from the user which
 * is controlled by LIMITS.maxSeedLength.
 */
const RANDOM_SEED_LENGTH = 10;

/* =========================================================
 * Runtime and validation limits
 * ========================================================= */

const LIMITS = Object.freeze({
  maxCards: 5000,
  maxCategories: 100,
  maxEditions: 100,
  maxDeckSize: 250,
  maxSeedLength: 128,
});

/* =========================================================
 * Card Pack Registrations
 * ========================================================= */

/*
 * Canonical Trail Talk card pack bundled with
 * Discussion Forge.
 *
 * Additional installed card packs will eventually
 * register themselves using the same structure.
 */
const TRAIL_TALK_PACK = Object.freeze({
  id: "trail-talk",

  paths: {
    manifest: "data/trail-talk/manifest.json",
    cards: "data/trail-talk/cards.json",
    categories: "data/trail-talk/categories.json",
    editions: "data/trail-talk/editions.json",
  },
});

/*
 * Small bundled trivia pack used to demonstrate and test
 * card-pack switching.
 */
const SAMPLE_TRIVIA_PACK = Object.freeze({
  id: "sample-trivia",

  paths: {
    manifest: "data/sample-trivia/manifest.json",
    cards: "data/sample-trivia/cards.json",
    categories: "data/sample-trivia/categories.json",
    editions: "data/sample-trivia/editions.json",
  },
});

/*
 * Registry of bundled card packs.
 *
 * The registry owns the default pack selection and all
 * card-pack definitions available to the application.
 */
const CARD_PACK_REGISTRY = Object.freeze({
  defaultCardPackId: "trail-talk",

  packs: [TRAIL_TALK_PACK, SAMPLE_TRIVIA_PACK],
});

/* =========================================================
 * Mutable application state
 * ========================================================= */

/*
 * This is the only intentionally mutable application-level
 * object. Card-pack and catalog data are validated before
 * being stored.
 */
const state = {
  activeCardPack: null,

  catalog: {
    cards: [],
    categories: [],
    editions: [],
  },

  generated: [],
  manifest: null,
  themeId: DEFAULT_THEME_ID,
};

/*
 * Cached references to required application UI elements.
 *
 * Looking up required DOM elements once keeps rendering code
 * concise, improves readability, and provides better editor
 * autocomplete. Each reference is resolved through
 * requireElement(), so missing IDs still fail immediately
 * during application startup rather than later during use.
 */
const ui = Object.freeze({
  generateButton: requireElement("generate"),

  printButton: requireElement("print"),

  randomSeedButton: requireElement("random-seed"),

  manifestButton: requireElement("download-manifest"),

  outputMode: requireElement("output-mode"),

  cardPackSelect: requireElement("card-pack"),

  themeSelect: requireElement("theme"),

  seedInput: requireElement("seed"),

  deckSizeInput: requireElement("deck-size"),

  builderSelectionSummary: requireElement("builder-selection-summary"),

  availableCardCount: requireElement("available-card-count"),

  selectedEditionCount: requireElement("selected-edition-count"),

  selectedCategoryCount: requireElement("selected-category-count"),

  editionOptions: requireElement("edition-options"),

  categoryOptions: requireElement("category-options"),

  previewOutput: requireElement("preview-output"),

  printOutput: requireElement("print-output"),

  status: requireElement("status"),
});

/* =========================================================
 * DOM access and application status
 * ========================================================= */

/*
 * Return an element by ID, or null when it does not exist.
 *
 * Most application code should use requireElement() instead
 * so missing required page structure fails immediately.
 */
function byId(id) {
  return document.getElementById(id);
}

/*
 * Return a required page element.
 *
 * Discussion Forge treats the IDs declared in index.html as
 * part of the application contract. Missing required elements
 */
function requireElement(id) {
  const element = byId(id);

  if (!element) {
    throw new Error(`Required page element not found: #${id}`);
  }

  return element;
}

/*
 * Replace the live status message shown to the user.
 *
 * The status element uses aria-live in index.html, so concise
 * updates are also announced by assistive technology.
 */
function setStatus(message) {
  ui.status.textContent = message;
}

/* =========================================================
 * Catalog loading safeguards
 * ========================================================= */

/*
 * Require a catalog array and enforce its maximum number
 * of records before validating individual entries.
 */
function requireCatalogArray(value, catalogName, maxItems) {
  if (!Array.isArray(value)) {
    throw new TypeError(`${catalogName} must be an array.`);
  }

  if (value.length > maxItems) {
    throw new RangeError(
      `${catalogName} cannot contain more than ${maxItems} records.`,
    );
  }

  return value;
}

/* =========================================================
 * Catalog loading
 * ========================================================= */

/*
 * Load, validate, cross-check, and store the bundled card,
 * category, and edition catalogs before the application
 * becomes interactive.
 */

/* ---------------------------------------------------------
 * Card-pack lookup
 * --------------------------------------------------------- */

/*
 * Return an installed card-pack definition by ID.
 *
 * Rejecting unknown IDs prevents callers from constructing
 * arbitrary resource paths.
 */
function requireCardPack(cardPackId) {
  const cardPack = CARD_PACK_REGISTRY.packs.find(
    (registeredCardPack) => registeredCardPack.id === cardPackId,
  );

  if (!cardPack) {
    throw new Error(`Unsupported card pack: ${cardPackId}`);
  }

  return cardPack;
}

/* ---------------------------------------------------------
 * JSON transport
 * --------------------------------------------------------- */

/*
 * Fetch one local JSON resource.
 *
 * Catalog requests use same-origin credentials and bypass
 * the browser cache so development changes are not masked by
 * stale data.
 */
async function fetchJson(path) {
  const response = await fetch(path, {
    credentials: "same-origin",
    cache: "no-store",
  });

  if (!response.ok) {
    throw new Error(`Unable to load ${path}: HTTP ${response.status}.`);
  }

  return response.json();
}

/* ---------------------------------------------------------
 * Card-pack loading
 * --------------------------------------------------------- */

/*
 * Load and validate one registered card pack.
 *
 * The returned data is fully validated but is not published
 * to application state.
 */
async function loadCardPack(cardPackId) {
  const registeredCardPack = requireCardPack(cardPackId);

  /*
   * Fetch all pack resources concurrently.
   */
  const [rawPackManifest, rawCards, rawCategories, rawEditions] =
    await Promise.all([
      fetchJson(registeredCardPack.paths.manifest),
      fetchJson(registeredCardPack.paths.cards),
      fetchJson(registeredCardPack.paths.categories),
      fetchJson(registeredCardPack.paths.editions),
    ]);

  /*
   * Validate card-pack metadata consumed by the runtime.
   */
  const cardPack = validateCardPackManifest(rawPackManifest);

  if (cardPack.id !== registeredCardPack.id) {
    throw new Error(
      `Card-pack manifest ID "${cardPack.id}" does not match registered ID "${registeredCardPack.id}".`,
    );
  }

  /*
   * Reject packs that require a newer Discussion Forge
   * application version than the current runtime.
   */
  if (
    compareSemver(APPLICATION.version, cardPack.minimumApplicationVersion) < 0
  ) {
    throw new Error(
      `Card pack "${cardPack.id}" requires Discussion Forge ` +
        `${cardPack.minimumApplicationVersion} or later, but ` +
        `the current version is ${APPLICATION.version}.`,
    );
  }

  /*
   * Validate and normalize catalog records.
   */
  const categories = requireCatalogArray(
    rawCategories,
    "categories",
    LIMITS.maxCategories,
  ).map(validateCategory);

  const editions = requireCatalogArray(
    rawEditions,
    "editions",
    LIMITS.maxEditions,
  ).map(validateEdition);

  const cards = requireCatalogArray(rawCards, "cards", LIMITS.maxCards).map(
    validateCard,
  );

  /*
   * Validate relationships and uniqueness across the trusted
   * catalog records.
   */
  validateCatalogIntegrity(cards, categories, editions, cardPack);

  return {
    cardPack,

    catalog: {
      cards,
      categories,
      editions,
    },
  };
}

/* ---------------------------------------------------------
 * Card-pack activation
 * --------------------------------------------------------- */

/*
 * Load a registered card pack and publish its validated
 * catalog to application state.
 */
async function activateCardPack(cardPackId) {
  const { cardPack, catalog } = await loadCardPack(cardPackId);

  state.activeCardPack = cardPack;
  state.catalog = catalog;

  /*
   * Refresh controls whose available values depend on the
   * active card pack.
   */
  renderOptions();
}

/* ---------------------------------------------------------
 * Catalog startup pipeline
 * --------------------------------------------------------- */

/*
 * Activate the default card pack and initialize application
 * presentation.
 */
async function loadData() {
  renderCardPackOptions();

  await activateCardPack(CARD_PACK_REGISTRY.defaultCardPackId);

  loadThemeStylesheet(state.themeId);
  renderThemeOptions();
}

/* =========================================================
 * Deck-builder controls
 * ========================================================= */

/*
 * Build and read the user controls that define which cards
 * are eligible for the next generated deck.
 */

/* ---------------------------------------------------------
 * Card-pack selector
 * --------------------------------------------------------- */

/*
 * Populate the Card Pack picker from the trusted registry.
 *
 * Registry IDs are converted to human-readable labels without
 * duplicating display metadata from individual pack manifests.
 */
function renderCardPackOptions() {
  const selector = ui.cardPackSelect;

  selector.replaceChildren();

  CARD_PACK_REGISTRY.packs.forEach((registeredCardPack) => {
    const option = document.createElement("option");

    option.value = registeredCardPack.id;

    option.textContent = registeredCardPack.id
      .split("-")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");

    selector.appendChild(option);
  });

  selector.value = CARD_PACK_REGISTRY.defaultCardPackId;
}

/* ---------------------------------------------------------
 * Edition and category options
 * --------------------------------------------------------- */

/*
 * Create one safely rendered checkbox option.
 */
function createCheckboxOption({ name, value, labelText, checked }) {
  const label = document.createElement("label");
  label.className = "option";

  const input = document.createElement("input");
  input.type = "checkbox";
  input.name = name;
  input.value = value;
  input.checked = checked;

  const text = document.createElement("span");
  text.textContent = labelText;

  label.append(input, text);

  return label;
}

/*
 * Populate the active edition and category choices from the
 * validated catalogs.
 *
 * The first active edition is selected initially, while all
 * active categories are selected.
 */
function renderOptions() {
  const editionContainer = ui.editionOptions;

  const categoryContainer = ui.categoryOptions;

  editionContainer.replaceChildren();
  categoryContainer.replaceChildren();

  state.catalog.editions
    .filter((edition) => edition.active)
    .forEach((edition, index) => {
      editionContainer.appendChild(
        createCheckboxOption({
          name: "edition",
          value: edition.id,
          labelText: edition.name,
          checked: index === 0,
        }),
      );
    });

  state.catalog.categories
    .filter((category) => category.active)
    .forEach((category) => {
      categoryContainer.appendChild(
        createCheckboxOption({
          name: "category",
          value: category.id,
          labelText: `${category.icon} ${category.name}`,
          checked: true,
        }),
      );
    });
  renderBuilderSelectionSummary();
}

/* ---------------------------------------------------------
 * Theme lookup
 * --------------------------------------------------------- */

/*
 * Return a validated theme package.
 *
 * Unknown theme identifiers fail immediately rather than
 * silently falling back to another theme.
 */
function requireTheme(themeId) {
  const theme = getTheme(themeId);

  if (!validateThemeDefinition(theme)) {
    throw new Error(`Unknown or invalid theme: ${themeId}`);
  }

  return theme;
}

/*
 * Return the default theme fallback icon.
 *
 * This is the second stage of the application's icon
 * fallback chain:
 *
 * Selected theme SVG
 *     ↓
 * Default theme SVG
 *     ↓
 * Catalog emoji
 */
function buildDefaultThemeIconPath(category) {
  const defaultTheme = requireTheme(DEFAULT_THEME_ID);

  return buildThemeIconPath(defaultTheme, category);
}

/* ---------------------------------------------------------
 * Theme asset resolution
 * --------------------------------------------------------- */

/*
 * Construct trusted paths to theme-owned assets.
 *
 * These helpers never concatenate arbitrary user input into
 * URLs. All paths originate from validated theme metadata.
 */

/*
 * Return the SVG icon path for one category.
 */
function buildThemeIconPath(theme, category) {
  return `${theme.assetRoot}/icons/${category.id}.svg`;
}

/*
 * Return the themed card-back artwork path.
 */
function buildThemeCardBackPath(theme) {
  return `${theme.assetRoot}/card-back.svg`;
}

/* ---------------------------------------------------------
 * Theme activation
 * --------------------------------------------------------- */

/*
 * Activate the selected theme stylesheet.
 *
 * Only one theme stylesheet is active at a time. Changing
 * themes replaces the existing stylesheet rather than
 * accumulating multiple active themes.
 */
function loadThemeStylesheet(themeId) {
  const theme = requireTheme(themeId);

  let stylesheet = document.getElementById(THEME_STYLESHEET_ID);

  if (!stylesheet) {
    stylesheet = document.createElement("link");

    stylesheet.id = THEME_STYLESHEET_ID;
    stylesheet.rel = "stylesheet";

    document.head.appendChild(stylesheet);
  }

  if (stylesheet.getAttribute("href") === theme.stylesheet) {
    return;
  }

  stylesheet.href = theme.stylesheet;
}

/* =========================================================
 * Theme subsystem
 * ========================================================= */

/*
 * Themes are trusted application packages.
 *
 * The application validates each theme definition before it
 * is used, constructs trusted asset paths beneath the theme's
 * asset root, dynamically loads the selected stylesheet, and
 * provides safe fallback behavior when optional assets are
 * unavailable.
 */

/* ---------------------------------------------------------
 * Theme selector
 * --------------------------------------------------------- */

/*
 * Populate the Theme picker using the validated registry.
 */
function renderThemeOptions() {
  const selector = ui.themeSelect;

  selector.replaceChildren();

  themes.forEach((theme) => {
    if (!validateThemeDefinition(theme)) {
      throw new Error(
        "The trusted theme registry contains an invalid theme definition.",
      );
    }

    const option = document.createElement("option");
    option.value = theme.id;
    option.textContent = theme.name;

    selector.appendChild(option);
  });

  const selectedTheme = getTheme(state.themeId);

  if (!validateThemeDefinition(selectedTheme)) {
    throw new Error(`Unknown or invalid initial theme: ${state.themeId}`);
  }

  selector.value = selectedTheme.id;
}

/*
 * Return the selected checkbox values for one builder option
 * group.
 *
 * Restricting accepted group names prevents arbitrary CSS
 * selectors from being constructed from caller input.
 */
function getSelectedOptionValues(name) {
  if (name !== "edition" && name !== "category") {
    throw new Error(`Unsupported option group requested: ${name}`);
  }

  const selected = [
    ...document.querySelectorAll(`input[name="${name}"]:checked`),
  ].map((input) => input.value);

  const records =
    name === "edition" ? state.catalog.editions : state.catalog.categories;

  const allowedIds = new Set(
    records.filter((record) => record.active).map((record) => record.id),
  );

  selected.forEach((value) => {
    if (!allowedIds.has(value)) {
      throw new Error(`Unsupported ${name} selection: ${value}`);
    }
  });

  return selected;
}

/*
 * Refresh live builder statistics from the current validated
 * catalog and content selections.
 */
function renderBuilderSelectionSummary() {
  const editions = getSelectedOptionValues("edition");
  const categories = getSelectedOptionValues("category");

  const eligibleCards = getEligibleCards(editions, categories);

  ui.availableCardCount.textContent = String(eligibleCards.length);
  ui.selectedEditionCount.textContent = String(editions.length);
  ui.selectedCategoryCount.textContent = String(categories.length);

  let requested = Number(ui.deckSizeInput.value);

  if (!Number.isInteger(requested) || requested < 1) {
    requested = 0;
  }

  const hasShortage = requested > eligibleCards.length;

  ui.availableCardCount.classList.toggle(
    "builder-summary-warning",
    hasShortage,
  );
  ui.builderSelectionSummary.classList.toggle(
    "builder-summary-shortage",
    hasShortage,
  );
}

/* ---------------------------------------------------------
 * Generation input validation
 * --------------------------------------------------------- */

/*
 * Require a whole-number playable-card count within the
 * application limit.
 */
function validateDeckSize(rawValue) {
  const size = Number(rawValue);

  if (!Number.isInteger(size)) {
    throw new TypeError("Deck size must be a whole number.");
  }

  if (size < 1 || size > LIMITS.maxDeckSize) {
    throw new RangeError(
      `Deck size must be between 1 and ${LIMITS.maxDeckSize}.`,
    );
  }

  return size;
}

/*
 * Normalize the generation seed.
 *
 * An empty value falls back to the demonstration seed so
 * generation remains deterministic.
 */
function validateSeed(rawSeed) {
  const normalized = typeof rawSeed === "string" ? rawSeed.trim() : "";

  const seed = normalized || "discussion-forge";

  if (seed.length > LIMITS.maxSeedLength) {
    throw new RangeError(
      `Seed cannot exceed ${LIMITS.maxSeedLength} characters.`,
    );
  }

  return seed;
}

/* =========================================================
 * Deck generation
 * ========================================================= */

/*
 * Convert the current builder configuration and validated
 * catalog into a reproducible, permanently positioned deck
 * and its downloadable manifest.
 */

/* ---------------------------------------------------------
 * Deterministic deck identity
 * --------------------------------------------------------- */

/*
 * Create the canonical fingerprint and human-readable Deck ID
 * for a generated playable deck.
 *
 * Set-like configuration arrays are sorted, while card order
 * is preserved because permanent deck position is meaningful.
 */
async function createDeckIdentity({
  cardPack,
  seed,
  editions,
  categories,
  requestedCardCount,
  cards,
}) {
  const identityPayload = {
    deck_identity_schema_version: DECK_IDENTITY_SCHEMA_VERSION,
    generator_version: GENERATOR_VERSION,
    card_pack_id: cardPack.id,
    card_pack_version: cardPack.version,
    seed,
    editions: [...editions].sort(),
    categories: [...categories].sort(),
    requested_card_count: requestedCardCount,

    /*
     * Ordered card identities make the fingerprint
     * describe the actual playable deck.
     */
    cards: cards.map((card) => ({
      card_uuid: card.card_uuid,
      content_version: card.content_version,
    })),
  };

  /*
   * Property order is intentionally fixed above, and
   * set-like arrays are sorted before serialization.
   */
  const canonicalPayload = JSON.stringify(identityPayload);

  const digest = await sha256Bytes(canonicalPayload);

  const fingerprint = bytesToHex(digest);

  const deckId = encodeBase32(digest).slice(0, HUMAN_DECK_ID_LENGTH);

  /*
   * Return both machine-readable and human-readable identities.
   */
  return {
    deckId,
    fingerprint,
    identityPayload,
  };
}

/*
 * Return true when a card is playable for the selected
 * editions and categories.
 *
 * A playable card must be active, approved, and associated
 * with at least one selected edition and one selected
 * category.
 */
function cardMatchesSelection(card, editions, categories) {
  return (
    card.active &&
    card.status === "approved" &&
    card.editions.some((editionId) => editions.includes(editionId)) &&
    card.categories.some((categoryId) => categories.includes(categoryId))
  );
}

/*
 * Return all currently playable cards for the supplied
 * edition and category selections.
 *
 * An empty edition or category selection produces no eligible
 * cards rather than treating the missing filter as unrestricted.
 */
function getEligibleCards(editions, categories) {
  if (editions.length === 0 || categories.length === 0) {
    return [];
  }

  return state.catalog.cards.filter((card) =>
    cardMatchesSelection(card, editions, categories),
  );
}

/*
 * Build the manifest describing one generated deck.
 *
 * This preserves the generation configuration, deterministic
 * identity fields, and immutable card-content snapshots used
 * to identify or reproduce the deck.
 */
function buildManifest({
  cardPack,
  deckUuid,
  deckId,
  fingerprint,
  seed,
  editions,
  categories,
  requested,
  generated,
}) {
  return {
    deck_uuid: deckUuid,
    deck_id: deckId,
    deck_fingerprint: fingerprint,
    deck_identity_schema_version: DECK_IDENTITY_SCHEMA_VERSION,

    generated_at: new Date().toISOString(),

    seed,

    generator_version: GENERATOR_VERSION,

    card_pack: {
      id: cardPack.id,
      version: cardPack.version,
    },

    configuration: {
      editions: [...editions],
      categories: [...categories],
      theme: state.themeId,
      requested_card_count: requested,
      playable_card_count: generated.length,
    },

    cards: generated.map((card) => ({
      deck_position: card.deck_position,

      card_uuid: card.card_uuid,

      content_version: card.content_version,

      content_snapshot: {
        prompt: card.content.prompt,

        instruction: card.content.instruction,
      },
    })),
  };
}

/*
 * Return a copy of the generated deck with permanent
 * one-based positions assigned.
 *
 * These positions become part of the deck identity and
 * remain stable for this generated deck.
 */
function assignDeckPositions(cards) {
  return cards.map((card, index) => ({
    deck_position: index + 1,
    ...card,
  }));
}

/*
 * Generate a secure UUID for one manifest instance.
 *
 * The deterministic Deck ID identifies the generated deck
 * configuration and card order. This UUID uniquely identifies
 * this particular generation event and downloaded manifest.
 */
function createDeckUuid() {
  if (
    !globalThis.crypto ||
    typeof globalThis.crypto.randomUUID !== "function"
  ) {
    throw new Error(
      "Secure UUID generation is not available in this browser context.",
    );
  }

  return globalThis.crypto.randomUUID();
}

/* ---------------------------------------------------------
 * Generation transaction
 * --------------------------------------------------------- */

/*
 * Generate one playable deck from the current builder state.
 *
 * The operation either completes with a matching generated
 * deck and manifest or reports a failure without exposing
 * partially generated output.
 */
async function generateDeck() {
  /*
   * Read and validate the requested configuration.
   */
  try {
    const editions = getSelectedOptionValues("edition");
    const categories = getSelectedOptionValues("category");

    const requested = validateDeckSize(ui.deckSizeInput.value);

    const seed = validateSeed(ui.seedInput.value);

    /*
     * Require at least one edition and one category.
     */
    if (editions.length === 0 || categories.length === 0) {
      setStatus("Select at least one edition and one category.");

      return;
    }

    /*
     * Find active, approved cards matching both the selected
     * edition set and category set.
     */
    const eligible = getEligibleCards(editions, categories);

    /*
     * Clear stale output when the current configuration has no
     * playable cards.
     */
    if (eligible.length === 0) {
      clearGeneratedOutput();

      setStatus("No cards match the selected editions and categories.");

      return;
    }

    /*
     * Select cards deterministically without mutating the
     * validated catalog order.
     */
    const chosen = seededShuffle(eligible, seed).slice(
      0,
      Math.min(requested, eligible.length),
    );

    /*
     * Assign a unique manifest-instance UUID in addition to the
     * deterministic Deck ID and fingerprint.
     */
    const deckUuid = createDeckUuid();

    const { deckId, fingerprint } = await createDeckIdentity({
      cardPack: state.activeCardPack,
      seed,
      editions,
      categories,
      requestedCardCount: requested,
      cards: chosen,
    });

    /*
     * Preserve permanent one-based positions for this generated
     * deck.
     */
    state.generated = assignDeckPositions(chosen);

    /*
     * Capture the generation configuration and immutable card
     * content snapshots needed to identify or reproduce the deck.
     */
    state.manifest = buildManifest({
      cardPack: state.activeCardPack,
      deckUuid,
      deckId,
      fingerprint,
      seed,
      editions,
      categories,
      requested,
      generated: state.generated,
    });

    /*
     * Report whether the requested deck size was fully satisfied.
     */
    setStatus(
      chosen.length < requested
        ? `Only ${chosen.length} eligible cards were available.`
        : `Generated ${chosen.length} playable cards.`,
    );

    /*
     * Render preview and print output from the same generated
     * deck state.
     */
    renderOutput();
  } catch (error) {
    /*
     * Fail visibly without exposing an uncaught generation error
     * to the user.
     */
    console.error(error);

    setStatus(
      error instanceof Error
        ? error.message
        : "The deck could not be generated.",
    );
  }
}

/* =========================================================
 * Shared rendering resources
 * ========================================================= */

/*
 * Resolve validated catalog relationships and create
 * theme-aware decorative assets shared by preview, print,
 * and Quick List output.
 */

/* ---------------------------------------------------------
 * Primary-category lookup
 * --------------------------------------------------------- */

/*
 * Return the validated primary category for one card.
 *
 * Catalog relationship validation should guarantee that the
 * category exists. This defensive check protects rendering if
 * application state is ever modified incorrectly.
 */
function categoryFor(card) {
  const category = state.catalog.categories.find(
    (candidate) => candidate.id === card.visual.primary_category,
  );

  if (!category) {
    throw new Error(
      `Card ${card.card_uuid} references a missing primary category.`,
    );
  }

  return category;
}

/* ---------------------------------------------------------
 * Category artwork
 * --------------------------------------------------------- */

/*
 * Create a category icon with graceful fallback behavior.
 *
 * Fallback order:
 *
 * 1. Selected theme SVG
 * 2. Default theme SVG
 * 3. Catalog emoji
 *
 * The wrapper may be decorative or may expose the category
 * name to assistive technology, depending on its use.
 */
function createCategoryIcon(
  category,
  { className = "", decorative = true, themeId = state.themeId } = {},
) {
  /*
   * Resolve the requested trusted theme.
   */
  const theme = requireTheme(themeId);

  /*
   * Create the semantic icon container.
   */
  const wrapper = document.createElement("span");

  if (className) {
    wrapper.className = className;
  }

  if (decorative) {
    wrapper.setAttribute("aria-hidden", "true");
  } else {
    wrapper.setAttribute("aria-label", category.name);
  }

  /*
   * Attempt the selected theme asset first.
   */
  const image = document.createElement("img");

  image.src = buildThemeIconPath(theme, category);

  image.alt = "";

  image.width = 32;
  image.height = 32;

  image.className = "category-svg-icon";

  /*
   * Fall through to the default theme, then to the catalog emoji.
   */
  image.onerror = () => {
    if (theme.id === DEFAULT_THEME_ID) {
      wrapper.textContent = category.icon;
      return;
    }

    image.onerror = () => {
      wrapper.textContent = category.icon;
    };

    image.src = buildDefaultThemeIconPath(category);
  };

  wrapper.appendChild(image);

  return wrapper;
}

/* ---------------------------------------------------------
 * Card-back artwork
 * --------------------------------------------------------- */

/*
 * Create the optional decorative card-back graphic.
 *
 * Fallback order:
 *
 * 1. Selected theme card-back.svg
 * 2. Default theme card-back.svg
 * 3. No graphic; preserve the complete text-only card back
 */
function createCardBackGraphic({ themeId = state.themeId } = {}) {
  const theme = requireTheme(themeId);

  const wrapper = document.createElement("div");

  wrapper.className = "card-back-main-graphic";

  /*
   * The image is decorative. The meaningful content
   * of the card back remains available as text.
   */
  wrapper.setAttribute("aria-hidden", "true");

  const image = document.createElement("img");

  image.className = "card-back-main-graphic-image";

  image.alt = "";

  image.src = buildThemeCardBackPath(theme);

  image.onerror = () => {
    /*
     * Do not request the same missing asset twice.
     */
    if (theme.id === DEFAULT_THEME_ID) {
      wrapper.remove();
      return;
    }

    const defaultTheme = requireTheme(DEFAULT_THEME_ID);

    image.onerror = () => {
      /*
       * Both assets are unavailable. Remove the
       * decorative graphic and retain the complete
       * text-only card back.
       */
      wrapper.remove();
    };

    image.src = buildThemeCardBackPath(defaultTheme);
  };

  wrapper.appendChild(image);

  return wrapper;
}

/* =========================================================
 * Canonical card renderers
 * ========================================================= */

/*
 * These functions create the physical card faces shared by
 * both interactive preview output and printable output.
 *
 * They render from the same generated deck state so preview
 * and print remain synchronized.
 */

/* ---------------------------------------------------------
 * Card front
 * --------------------------------------------------------- */

/*
 * Render one complete card front:
 *
 * - category banner
 * - banner icon and name
 * - center icon
 * - prompt
 * - optional instruction
 * - permanent Deck ID and position footer
 */
function renderFrontCard(card, { themeId = state.themeId } = {}) {
  /*
   * Resolve the card's primary category and requested theme.
   */
  const category = categoryFor(card);
  const theme = requireTheme(themeId);

  /*
   * Create the physical card container.
   */
  const article = document.createElement("article");

  article.classList.add("play-card", "card-front", theme.className);

  /*
   * Build the category banner.
   */
  const band = document.createElement("div");

  band.classList.add("card-band", `category-${category.id}`);

  const bandIcon = createCategoryIcon(category, {
    className: "category-icon",
  });

  const bandName = document.createElement("span");

  bandName.className = "category-name";
  bandName.textContent = category.name;

  band.append(bandIcon, bandName);

  /*
   * Build the centered prompt content.
   */
  const body = document.createElement("div");
  body.className = "card-body";

  const bodyContent = document.createElement("div");

  const cardIcon = createCategoryIcon(category, {
    className: "card-icon",
  });

  const prompt = document.createElement("p");
  prompt.className = "card-prompt";
  prompt.textContent = card.content.prompt;

  bodyContent.append(cardIcon, prompt);

  /*
   * Add optional play guidance only when present.
   */
  if (card.content.instruction) {
    const instruction = document.createElement("p");

    instruction.className = "card-instruction";

    instruction.textContent = card.content.instruction;

    bodyContent.appendChild(instruction);
  }

  body.appendChild(bodyContent);

  /*
   * Add the deterministic Deck ID and permanent position.
   */
  const footer = document.createElement("div");

  footer.className = "card-footer";

  const footerText = document.createElement("span");

  footerText.textContent =
    `${state.manifest.deck_id} · ` +
    `${card.deck_position}/` +
    `${state.generated.length}`;

  footer.appendChild(footerText);

  article.append(band, body, footer);

  return article;
}

/* ---------------------------------------------------------
 * Card back
 * --------------------------------------------------------- */

/*
 * Render one complete card back:
 *
 * - optional hole-punch guide
 * - theme-owned decorative artwork
 * - application-owned title
 * - theme-styled divider
 * - card-pack title
 * - card-pack tagline
 * - card-pack brand
 */
function renderBackCard({
  showPunchGuide = true,
  themeId = state.themeId,
} = {}) {
  const theme = requireTheme(themeId);

  if (!state.activeCardPack) {
    throw new Error("No validated card pack is active.");
  }

  const cardBack = state.activeCardPack.cardBack;

  /*
   * Create the theme-styled divider as a standalone element.
   */
  const divider = document.createElement("div");

  divider.className = "card-back-divider";

  divider.setAttribute("aria-hidden", "true");

  /*
   * Create the physical card container.
   */
  const article = document.createElement("article");

  article.classList.add("play-card", "card-back", theme.className);

  /*
   * Add the application-owned hole-punch guide when requested.
   */
  if (showPunchGuide) {
    const punchGuide = document.createElement("div");

    punchGuide.className = "punch-safe punch-safe-back";

    punchGuide.title = "Optional hole-punch safe area";

    article.appendChild(punchGuide);
  }

  /*
   * Build the semantic card-back content stack.
   */
  const content = document.createElement("div");

  content.className = "card-back-content";

  /*
   * Add optional theme artwork with graceful fallback.
   */
  const mainGraphic = createCardBackGraphic({
    themeId,
  });

  /*
   * Add identity text supplied by the active card pack.
   */
  const heading = document.createElement("h3");

  heading.className = "card-back-title";

  heading.textContent = cardBack.title;

  const tagline = document.createElement("p");

  tagline.className = "card-back-tagline";

  /*
   * Render exactly two optional tagline positions.
   *
   * Empty strings remain as empty spans so a card pack may
   * intentionally use only the upper line, only the lower
   * line, both lines, or neither line.
   */
  const taglineLineOne = document.createElement("span");

  taglineLineOne.textContent = cardBack.tagline[0];

  const taglineLineTwo = document.createElement("span");

  taglineLineTwo.textContent = cardBack.tagline[1];

  tagline.append(taglineLineOne, taglineLineTwo);

  const brand = document.createElement("p");

  brand.className = "card-back-brand";

  brand.textContent = cardBack.brand;

  content.append(mainGraphic, heading, divider, tagline, brand);

  article.appendChild(content);

  return article;
}

/*
 * Clear all generated deck state and rendered output.
 *
 * This resets the application after generation errors
 * or when the current builder configuration produces
 * no playable cards.
 */
function clearGeneratedOutput() {
  state.generated = [];
  state.manifest = null;

  ui.previewOutput.replaceChildren();
  ui.printOutput.replaceChildren();
}

/*
 * Render one interactive preview card.
 *
 * Preview cards reuse the canonical front and back renderers
 * so the preview always matches printed output.
 */
function renderPreviewCard(card) {
  /*
   * Create the interactive preview container.
   */
  const wrapper = document.createElement("div");

  wrapper.className = "preview-card";
  wrapper.setAttribute("role", "button");
  wrapper.tabIndex = 0;

  wrapper.setAttribute("aria-pressed", "false");

  wrapper.setAttribute(
    "aria-label",
    `Flip card ${card.deck_position} to view the back`,
  );

  const inner = document.createElement("div");

  inner.className = "preview-card-inner";

  const frontSide = document.createElement("div");

  frontSide.className = "preview-card-side preview-card-front";

  /*
   * Build the canonical front card face.
   */
  frontSide.appendChild(renderFrontCard(card));

  const backSide = document.createElement("div");

  backSide.className = "preview-card-side preview-card-back";

  /*
   * Build the canonical back card face.
   */
  backSide.appendChild(
    renderBackCard({
      showPunchGuide: true,
    }),
  );

  inner.append(frontSide, backSide);
  wrapper.appendChild(inner);

  return wrapper;
}

/* =========================================================
 * Output coordination
 * ========================================================= */

/*
 * Render every presentation of the generated deck from the
 * same application state.
 *
 * Preview and printable output are always regenerated
 * together.
 */
function renderOutput() {
  renderPreview();
  renderPrintOutput();
}

/*
 * Render the summary panel shown above the preview.
 *
 * The panel reports the generated deck identity and the
 * configuration used to create it.
 */
function renderPreviewStatus() {
  if (!state.manifest) {
    return null;
  }

  const configuration = state.manifest.configuration;

  const theme = getTheme(state.themeId);

  if (!validateThemeDefinition(theme)) {
    throw new Error(`Unknown or invalid theme: ${state.themeId}`);
  }

  const editionNames = configuration.editions
    .map((editionId) =>
      state.catalog.editions.find((edition) => edition.id === editionId),
    )
    .filter(Boolean)
    .map((edition) => edition.name);

  const categoryNames = configuration.categories
    .map((categoryId) =>
      state.catalog.categories.find((category) => category.id === categoryId),
    )
    .filter(Boolean)
    .map((category) => category.name);

  const header = document.createElement("header");

  header.className = "preview-status";

  const headingRow = document.createElement("div");

  headingRow.className = "preview-status-heading";

  const headingText = document.createElement("div");

  const eyebrow = document.createElement("p");

  eyebrow.className = "preview-status-eyebrow";

  eyebrow.textContent = "Deck Preview";

  const heading = document.createElement("h2");

  heading.textContent = `Deck ${state.manifest.deck_id}`;

  headingText.append(eyebrow, heading);

  const count = document.createElement("span");

  count.className = "preview-status-count";

  count.textContent = `${state.generated.length} cards`;

  headingRow.append(headingText, count);

  const details = document.createElement("dl");

  details.className = "preview-status-details";

  details.append(
    createStatusDetail("Theme", theme.name),

    createStatusDetail("Editions", editionNames.join(", ")),

    createStatusDetail("Categories", categoryNames.join(", ")),

    createStatusDetail("Seed", state.manifest.seed, {
      useCode: true,
    }),
  );

  header.append(headingRow, details);

  return header;
}

/* =========================================================
 * Interactive preview
 * ========================================================= */

/*
 * The screen preview is a complete interactive view of the
 * generated deck.
 *
 * Unlike printable output, preview cards can be flipped to
 * inspect both sides before printing.
 */

/* ---------------------------------------------------------
 * Preview status panel
 * --------------------------------------------------------- */

/*
 * Create one labeled value displayed in the preview summary.
 */
function createStatusDetail(label, value, { useCode = false } = {}) {
  const wrapper = document.createElement("div");

  const term = document.createElement("dt");

  term.textContent = label;

  const description = document.createElement("dd");

  if (useCode) {
    const code = document.createElement("code");

    code.textContent = value;
    description.appendChild(code);
  } else {
    description.textContent = value;
  }

  wrapper.append(term, description);

  return wrapper;
}

/* ---------------------------------------------------------
 * Preview coordinator
 * --------------------------------------------------------- */

/*
 * Render the complete interactive preview.
 *
 * This function owns only preview composition. Individual
 * cards and status details are delegated to helper
 * functions.
 */
function renderPreview() {
  const mode = ui.outputMode.value;

  const output = ui.previewOutput;

  output.replaceChildren();

  const status = renderPreviewStatus();

  if (status) {
    output.appendChild(status);
  }

  if (mode === "list") {
    renderQuickList(output);

    return;
  }

  const previewGrid = document.createElement("div");

  previewGrid.className = "card-grid preview-card-grid";

  state.generated.forEach((card) => {
    previewGrid.appendChild(renderPreviewCard(card));
  });

  output.appendChild(previewGrid);

  previewGrid.querySelectorAll(".preview-card").forEach((cardElement) => {
    cardElement.addEventListener("click", () => {
      togglePreviewCard(cardElement);
    });

    cardElement.addEventListener("keydown", (event) => {
      if (event.key === "Enter" || event.key === " ") {
        event.preventDefault();

        togglePreviewCard(cardElement);
      }
    });
  });
}

/* ---------------------------------------------------------
 * Preview interaction
 * --------------------------------------------------------- */

/*
 * Flip one preview card between its front and back faces.
 */
function togglePreviewCard(cardElement) {
  const isFlipped = cardElement.classList.toggle("is-flipped");

  cardElement.setAttribute("aria-pressed", String(isFlipped));

  cardElement.setAttribute(
    "aria-label",
    isFlipped ? "Flip card to view the front" : "Flip card to view the back",
  );
}

/* =========================================================
 * Quick List
 * ========================================================= */

/*
 * Render a compact printable reference list.
 *
 * The Quick List preserves permanent Deck IDs and positions
 * while minimizing paper usage for last-minute trips.
 */
function renderQuickList(container) {
  const list = document.createElement("div");

  list.className = "quick-list";

  /*
   * Populate the supplied Quick List container.
   */
  state.generated.forEach((card) => {
    const category = categoryFor(card);

    const article = document.createElement("article");

    article.className = "list-item";

    const metadata = document.createElement("div");

    metadata.className = "list-meta";

    metadata.append(
      document.createTextNode(
        `${state.manifest.deck_id} · ` +
          `${card.deck_position}/` +
          `${state.generated.length}`,
      ),
      document.createElement("br"),
      createCategoryIcon(category, {
        className: "list-category-icon",
      }),
      document.createTextNode(` ${category.name}`),
    );

    const prompt = document.createElement("p");

    prompt.className = "list-prompt";

    const strong = document.createElement("strong");

    strong.textContent = card.content.prompt;

    prompt.appendChild(strong);

    if (card.content.instruction) {
      prompt.append(
        document.createElement("br"),
        document.createTextNode(card.content.instruction),
      );
    }

    article.append(metadata, prompt);
    list.appendChild(article);
  });

  container.appendChild(list);
}

/* =========================================================
 * Printable output
 * ========================================================= */

/*
 * Render duplex-ready pages.
 *
 * Front pages are immediately followed by their matching
 * back pages to support long-edge duplex printing.
 */
function renderPrintOutput() {
  const mode = ui.outputMode.value;

  const output = ui.printOutput;

  output.replaceChildren();

  /*
   * Quick List mode bypasses card rendering entirely.
   */
  if (mode === "list") {
    renderQuickList(output);

    return;
  }

  const cardsPerPage = 6;

  /*
   * Group cards into printable six-card sheets.
   */
  const cardGroups = chunkArray(state.generated, cardsPerPage);

  cardGroups.forEach((cards) => {
    const firstPosition = cards[0].deck_position;

    const lastPosition = cards[cards.length - 1].deck_position;

    /*
     * Create the front page for this sheet.
     */
    const frontPage = document.createElement("section");

    frontPage.className = "print-page front-page";

    frontPage.dataset.pageType = "front";

    frontPage.dataset.cardRange = `${firstPosition}-${lastPosition}`;

    const frontGrid = document.createElement("div");

    frontGrid.className = "card-grid";

    cards.forEach((card) => {
      frontGrid.appendChild(renderFrontCard(card));
    });

    frontPage.appendChild(frontGrid);
    output.appendChild(frontPage);

    /*
     * Create the matching back page.
     */
    const backPage = document.createElement("section");

    backPage.className = "print-page back-page";

    backPage.dataset.pageType = "back";

    backPage.dataset.cardRange = `${firstPosition}-${lastPosition}`;

    const backGrid = document.createElement("div");

    backGrid.className = "card-grid";

    cards.forEach(() => {
      backGrid.appendChild(renderBackCard());
    });

    backPage.appendChild(backGrid);
    output.appendChild(backPage);
  });
}

/* =========================================================
 * Manifest export
 * ========================================================= */

/*
 * Download the generated deck manifest.
 *
 * The manifest contains the information required to identify
 * or reproduce the generated deck independently of the
 * printed cards.
 */
function downloadManifest() {
  if (!state.manifest) {
    setStatus("Generate a deck first.");

    return;
  }

  const blob = new Blob([JSON.stringify(state.manifest, null, 2)], {
    type: "application/json",
  });

  const url = URL.createObjectURL(blob);

  const anchor = document.createElement("a");

  anchor.href = url;

  anchor.download =
    `discussion-forge-${state.manifest.deck_id}` + "-manifest.json";

  anchor.hidden = true;

  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();

  window.setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 0);
}

/* =========================================================
 * Application lifecycle
 * ========================================================= */

/*
 * Register user interactions and perform application
 * startup.
 *
 * Initialization order:
 *
 *   1. Register event handlers.
 *   2. Load and validate catalogs.
 *   3. Activate the default theme.
 *   4. Render the initial builder.
 */

/* =========================================================
 * Event handlers
 * ========================================================= */

/*
 * Generate a new secure, human-readable seed and place it
 * into the builder control.
 */
function handleRandomSeed() {
  ui.seedInput.value = randomCode(RANDOM_SEED_LENGTH);
}

/*
 * Open the browser's print dialog.
 */
function handlePrint() {
  window.print();
}

/*
 * Refresh builder statistics when edition or category
 * selections change.
 */
function handleBuilderSelectionChange() {
  renderBuilderSelectionSummary();
}

/*
 * Download the current generated-deck manifest.
 */
function handleManifestDownload() {
  downloadManifest();
}

/*
 * Re-render an existing generated deck when the user changes
 * between Poker Cards and Quick List modes.
 */
function handleOutputModeChange() {
  if (state.generated.length > 0) {
    renderOutput();
  }
}

/*
 * Activate the selected card pack and clear output generated
 * from the previously active pack.
 *
 * A rejected selection restores the previously active pack
 * without disturbing trusted runtime state.
 */
async function handleCardPackChange(event) {
  const requestedCardPackId = event.target.value;

  const previousCardPackId =
    state.activeCardPack?.id ?? CARD_PACK_REGISTRY.defaultCardPackId;

  if (requestedCardPackId === previousCardPackId) {
    return;
  }

  try {
    await activateCardPack(requestedCardPackId);

    clearGeneratedOutput();

    setStatus(`Loaded card pack: ${state.activeCardPack.displayName}.`);
  } catch (error) {
    console.error(error);

    event.target.value = previousCardPackId;

    setStatus("The selected card pack could not be loaded safely.");
  }
}

/*
 * Activate the selected theme and re-render existing output.
 *
 * A rejected theme selection restores the previously active
 * theme without modifying generated deck state.
 */
function handleThemeChange(event) {
  const requestedThemeId = event.target.value;

  try {
    const selectedTheme = requireTheme(requestedThemeId);

    state.themeId = selectedTheme.id;

    loadThemeStylesheet(state.themeId);

    if (state.manifest) {
      state.manifest.configuration.theme = state.themeId;
    }

    if (state.generated.length > 0) {
      renderOutput();
    }
  } catch (error) {
    console.error(error);

    setStatus("The selected theme is not available.");

    event.target.value = state.themeId;
  }
}

/* =========================================================
 * Event registration
 * ========================================================= */

/*
 * Connect page controls to their application handlers.
 */
function registerEventListeners() {
  ui.generateButton.addEventListener("click", generateDeck);

  ui.randomSeedButton.addEventListener("click", handleRandomSeed);

  ui.printButton.addEventListener("click", handlePrint);

  ui.manifestButton.addEventListener("click", handleManifestDownload);

  ui.outputMode.addEventListener("change", handleOutputModeChange);

  ui.deckSizeInput.addEventListener("input", renderBuilderSelectionSummary);

  ui.editionOptions.addEventListener("change", handleBuilderSelectionChange);

  ui.categoryOptions.addEventListener("change", handleBuilderSelectionChange);

  ui.cardPackSelect.addEventListener("change", handleCardPackChange);

  ui.themeSelect.addEventListener("change", handleThemeChange);
}

registerEventListeners();

loadData().catch((error) => {
  console.error(error);

  clearGeneratedOutput();

  setStatus(
    "The card catalog could not be loaded safely. " +
      "Check the browser console for details.",
  );
});
