/*
 * Trail Talk application
 *
 * This module owns application configuration, catalog
 * validation, deck generation, rendering, user interaction,
 * manifest creation, and application startup.
 */

/* =========================================================
 * Imports
 * ========================================================= */

import {
  bytesToHex,
  chunkArray,
  encodeBase32,
  randomCode,
  seededShuffle,
  sha256Bytes,
} from "./utils.js";

import { getTheme, themes } from "../themes/index.js";

/* =========================================================
 * Application identity
 * ========================================================= */

/*
 * Canonical application-owned text used on card backs.
 *
 * Themes may style this text but may not redefine the
 * application title, tagline, or brand.
 */
const APP_IDENTITY = Object.freeze({
  title: "TRAIL TALK",
  taglineLineOne: "Real Questions.",
  taglineLineTwo: "Real Connections.",
  brand: "Overlanding Atlas",
});

/* =========================================================
 * Version and deck-identity contracts
 * ========================================================= */

/*
 * Increment this only when the canonical deck-identity
 * payload or fingerprint algorithm changes.
 */
const DECK_IDENTITY_VERSION = 1;

/*
 * Trail Talk generator version recorded in manifests and
 * deterministic deck-identity payloads.
 */
const GENERATOR_VERSION = "0.2.0-alpha3";

/*
 * Version of the bundled catalog content used to generate
 * a deck.
 */
const CATALOG_VERSION = "2026.08.01";

/*
 * Number of Base32 characters exposed as the human-readable
 * deterministic Deck ID.
 */
const HUMAN_DECK_ID_LENGTH = 10;

/* =========================================================
 * Theme defaults
 * ========================================================= */

/*
 * Trail Blue is the canonical fallback theme.
 */
const DEFAULT_THEME_ID = "trail-blue";

/*
 * DOM ID used for the dynamically loaded theme stylesheet.
 */
const THEME_STYLESHEET_ID = "active-theme-stylesheet";

/* =========================================================
 * Runtime defaults
 * ========================================================= */

/*
 * Number of characters generated by the Random Seed button.
 *
 * This controls the application's generated seed format,
 * not the maximum seed length accepted from the user.
 */
const RANDOM_SEED_LENGTH = 10;

/* =========================================================
 * Runtime and validation limits
 * ========================================================= */

const LIMITS = Object.freeze({
  maxCards: 5000,
  maxCategories: 100,
  maxEditions: 100,
  maxDeckSize: 250,
  maxSeedLength: 128,
  maxPromptLength: 500,
  maxInstructionLength: 1000,
  maxDisplayNameLength: 100,
  maxIconLength: 16,
});

/* =========================================================
 * Catalog allowlists
 * ========================================================= */

const ALLOWED_CARD_TYPES = new Set([
  "question",
  "story",
  "lightning",
  "wildcard",
]);

const ALLOWED_CARD_STATUSES = new Set([
  "draft",
  "pending",
  "approved",
  "rejected",
  "retired",
]);

const ALLOWED_RESPONSE_STYLES = new Set([
  "discussion",
  "story",
  "quick",
  "challenge",
]);

const ALLOWED_ANSWER_LENGTHS = new Set(["short", "medium", "long"]);

const ALLOWED_EXPERIENCE_LEVELS = new Set(["beginner", "experienced"]);

const ALLOWED_AUDIENCES = new Set(["general"]);

const ALLOWED_GROUP_FAMILIARITY = new Set(["new-group", "friends"]);

const ALLOWED_SENSITIVITY_LEVELS = new Set(["low", "medium", "high"]);

const ALLOWED_SOURCES = new Set(["original", "community"]);

/* =========================================================
 * Validation patterns
 * ========================================================= */

/*
 * Lowercase kebab-case identifiers used by categories,
 * editions, themes, and other trusted registry values.
 */
const ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/*
 * UUID validation accepts RFC-compatible UUID versions
 * 1 through 8 and the standard variant bits.
 */
const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/*
 * Theme package versions currently use stable semantic
 * versions without prerelease or build suffixes.
 */
const SEMVER_PATTERN = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/;

/*
 * Six-digit hexadecimal color values used by catalog data.
 */
const HEX_COLOR_PATTERN = /^#[0-9a-f]{6}$/i;

/* =========================================================
 * Mutable application state
 * ========================================================= */

/*
 * This is the only intentionally mutable application-level
 * object. Catalog records are validated before being stored.
 */
const state = {
  cards: [],
  categories: [],
  editions: [],
  generated: [],
  manifest: null,
  themeId: DEFAULT_THEME_ID,
};

/*
 * Cached references to required application UI elements.
 *
 * Looking up required DOM elements once keeps rendering code
 * concise, improves readability, and provides better editor
 * autocomplete. Each reference is resolved through
 * requireElement(), so missing IDs still fail immediately
 * during application startup rather than later during use.
 */
const ui = Object.freeze({
  generateButton: requireElement("generate"),

  printButton: requireElement("print"),

  randomSeedButton: requireElement("random-seed"),

  manifestButton: requireElement("download-manifest"),

  outputMode: requireElement("output-mode"),

  themeSelect: requireElement("theme"),

  seedInput: requireElement("seed"),

  deckSizeInput: requireElement("deck-size"),

  editionOptions: requireElement("edition-options"),

  categoryOptions: requireElement("category-options"),

  previewOutput: requireElement("preview-output"),

  printOutput: requireElement("print-output"),

  status: requireElement("status"),
});

/* =========================================================
 * DOM access and application status
 * ========================================================= */

/*
 * Return an element by ID, or null when it does not exist.
 *
 * Most application code should use requireElement() instead
 * so missing required page structure fails immediately.
 */
function byId(id) {
  return document.getElementById(id);
}

/*
 * Return a required page element.
 *
 * Trail Talk treats the IDs declared in index.html as part
 * of the application contract. Missing required elements
 * stop processing rather than allowing partial operation.
 */
function requireElement(id) {
  const element = byId(id);

  if (!element) {
    throw new Error(`Required page element not found: #${id}`);
  }

  return element;
}

/*
 * Replace the live status message shown to the user.
 *
 * The status element uses aria-live in index.html, so concise
 * updates are also announced by assistive technology.
 */
function setStatus(message) {
  ui.status.textContent = message;
}

/* =========================================================
 * Generic validation helpers
 * ========================================================= */

/*
 * These helpers validate and normalize untrusted values
 * before application code stores or renders them.
 *
 * They throw descriptive errors rather than returning
 * partially valid data.
 */

/*
 * Return true only for non-null, non-array objects.
 */
function isPlainObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/*
 * Require a plain object and return it unchanged.
 */
function requireObject(value, fieldName) {
  if (!isPlainObject(value)) {
    throw new TypeError(`${fieldName} must be an object.`);
  }

  return value;
}

/*
 * Require, trim, constrain, and optionally pattern-check
 * a string.
 */
function requireString(
  value,
  fieldName,
  { minLength = 1, maxLength = 500, pattern = null } = {},
) {
  if (typeof value !== "string") {
    throw new TypeError(`${fieldName} must be a string.`);
  }

  const normalized = value.trim();

  if (normalized.length < minLength) {
    throw new RangeError(
      `${fieldName} must contain at least ${minLength} character(s).`,
    );
  }

  if (normalized.length > maxLength) {
    throw new RangeError(`${fieldName} cannot exceed ${maxLength} characters.`);
  }

  if (pattern && !pattern.test(normalized)) {
    throw new TypeError(`${fieldName} has an invalid format.`);
  }

  return normalized;
}

/*
 * Normalize an absent optional string to null.
 *
 * Present values receive the same validation as required
 * strings.
 */
function optionalString(value, fieldName, { maxLength = 500 } = {}) {
  if (value === undefined || value === null || value === "") {
    return null;
  }

  return requireString(value, fieldName, {
    minLength: 1,
    maxLength,
  });
}

/*
 * Require an actual Boolean value.
 *
 * Truthy and falsy substitutes such as 1, 0, or strings
 * are intentionally rejected.
 */
function requireBoolean(value, fieldName) {
  if (typeof value !== "boolean") {
    throw new TypeError(`${fieldName} must be true or false.`);
  }

  return value;
}

/*
 * Require an integer greater than zero.
 */
function requirePositiveInteger(value, fieldName) {
  if (!Number.isInteger(value) || value < 1) {
    throw new TypeError(`${fieldName} must be a positive integer.`);
  }

  return value;
}

/*
 * Require a non-empty, size-limited array of validated
 * strings.
 */
function requireStringArray(
  value,
  fieldName,
  { maxItems = 100, itemPattern = null } = {},
) {
  if (!Array.isArray(value)) {
    throw new TypeError(`${fieldName} must be an array.`);
  }

  if (value.length === 0) {
    throw new RangeError(`${fieldName} cannot be empty.`);
  }

  if (value.length > maxItems) {
    throw new RangeError(
      `${fieldName} cannot contain more than ${maxItems} items.`,
    );
  }

  return value.map((item, index) =>
    requireString(item, `${fieldName}[${index}]`, {
      minLength: 1,
      maxLength: 100,
      pattern: itemPattern,
    }),
  );
}

/*
 * Require an array whose normalized string values all
 * appear in a trusted allowlist.
 */
function requireAllowedStringArray(value, fieldName, allowedValues) {
  const items = requireStringArray(value, fieldName, {
    maxItems: allowedValues.size,
    itemPattern: ID_PATTERN,
  });

  items.forEach((item) => {
    if (!allowedValues.has(item)) {
      throw new TypeError(
        `${fieldName} contains an unsupported value: "${item}".`,
      );
    }
  });

  return items;
}

/*
 * Require a parseable timestamp and return it as a Date.
 *
 * Callers normalize accepted timestamps with toISOString()
 * before storing them.
 */
function requireIsoTimestamp(value, fieldName) {
  const timestamp = requireString(value, fieldName, {
    maxLength: 40,
  });

  const parsed = new Date(timestamp);

  if (Number.isNaN(parsed.getTime())) {
    throw new TypeError(`${fieldName} must be a valid ISO timestamp.`);
  }

  return parsed;
}

/*
 * Require a catalog array and enforce its maximum number
 * of records before validating individual entries.
 */
function requireCatalogArray(value, catalogName, maxItems) {
  if (!Array.isArray(value)) {
    throw new TypeError(`${catalogName} must be an array.`);
  }

  if (value.length > maxItems) {
    throw new RangeError(
      `${catalogName} cannot contain more than ${maxItems} records.`,
    );
  }

  return value;
}

/* =========================================================
 * Catalog record validation
 * ========================================================= */

/*
 * These functions convert untrusted JSON records into
 * normalized application records.
 *
 * Only the properties explicitly returned by each validator
 * are preserved. Unknown properties are discarded.
 */

/* ---------------------------------------------------------
 * Category records
 * --------------------------------------------------------- */

/*
 * Validate and normalize one category catalog record.
 */
function validateCategory(rawCategory, index) {
  const category = requireObject(rawCategory, `categories[${index}]`);

  return {
    id: requireString(category.id, `categories[${index}].id`, {
      maxLength: 64,
      pattern: ID_PATTERN,
    }),

    name: requireString(category.name, `categories[${index}].name`, {
      maxLength: LIMITS.maxDisplayNameLength,
    }),

    short_name: optionalString(
      category.short_name,
      `categories[${index}].short_name`,
      {
        maxLength: LIMITS.maxDisplayNameLength,
      },
    ),

    icon: requireString(category.icon, `categories[${index}].icon`, {
      maxLength: LIMITS.maxIconLength,
    }),

    color: requireString(category.color, `categories[${index}].color`, {
      maxLength: 7,
      pattern: HEX_COLOR_PATTERN,
    }),

    active: requireBoolean(category.active, `categories[${index}].active`),
  };
}

/* ---------------------------------------------------------
 * Edition records
 * --------------------------------------------------------- */

/*
 * Validate and normalize one edition catalog record.
 */
function validateEdition(rawEdition, index) {
  const edition = requireObject(rawEdition, `editions[${index}]`);

  return {
    id: requireString(edition.id, `editions[${index}].id`, {
      maxLength: 64,
      pattern: ID_PATTERN,
    }),

    name: requireString(edition.name, `editions[${index}].name`, {
      maxLength: LIMITS.maxDisplayNameLength,
    }),

    description: optionalString(
      edition.description,
      `editions[${index}].description`,
      {
        maxLength: 500,
      },
    ),

    active: requireBoolean(edition.active, `editions[${index}].active`),
  };
}

/* ---------------------------------------------------------
 * Card records
 * --------------------------------------------------------- */

/*
 * Validate and normalize one card catalog record.
 *
 * Card validation includes:
 * - identity and lifecycle metadata
 * - prompt and instruction content
 * - category and edition relationships
 * - response and audience classifications
 * - contributor credit
 * - timestamps and content versioning
 */
function validateCard(rawCard, index) {
  /*
   * Required nested record sections.
   */
  const card = requireObject(rawCard, `cards[${index}]`);

  const content = requireObject(card.content, `cards[${index}].content`);

  const visual = requireObject(card.visual, `cards[${index}].visual`);

  const credit = requireObject(card.credit, `cards[${index}].credit`);

  /*
   * Single-value classifications.
   *
   * Each value must satisfy the identifier format and appear
   * in its corresponding trusted allowlist.
   */
  const type = requireString(card.type, `cards[${index}].type`, {
    maxLength: 32,
    pattern: ID_PATTERN,
  });

  if (!ALLOWED_CARD_TYPES.has(type)) {
    throw new TypeError(
      `cards[${index}].type contains an unsupported card type.`,
    );
  }

  const status = requireString(card.status, `cards[${index}].status`, {
    maxLength: 32,
    pattern: ID_PATTERN,
  });

  if (!ALLOWED_CARD_STATUSES.has(status)) {
    throw new TypeError(
      `cards[${index}].status contains an unsupported status.`,
    );
  }

  const responseStyle = requireString(
    card.response_style,
    `cards[${index}].response_style`,
    {
      maxLength: 32,
      pattern: ID_PATTERN,
    },
  );

  if (!ALLOWED_RESPONSE_STYLES.has(responseStyle)) {
    throw new TypeError(
      `cards[${index}].response_style contains an unsupported value.`,
    );
  }

  const answerLength = requireString(
    card.answer_length,
    `cards[${index}].answer_length`,
    {
      maxLength: 32,
      pattern: ID_PATTERN,
    },
  );

  if (!ALLOWED_ANSWER_LENGTHS.has(answerLength)) {
    throw new TypeError(
      `cards[${index}].answer_length contains an unsupported value.`,
    );
  }

  const sensitivity = requireString(
    card.sensitivity,
    `cards[${index}].sensitivity`,
    {
      maxLength: 32,
      pattern: ID_PATTERN,
    },
  );

  if (!ALLOWED_SENSITIVITY_LEVELS.has(sensitivity)) {
    throw new TypeError(
      `cards[${index}].sensitivity contains an unsupported value.`,
    );
  }

  const source = requireString(card.source, `cards[${index}].source`, {
    maxLength: 32,
    pattern: ID_PATTERN,
  });

  if (!ALLOWED_SOURCES.has(source)) {
    throw new TypeError(
      `cards[${index}].source contains an unsupported value.`,
    );
  }

  /*
   * Multi-value audience and experience classifications.
   */
  const experienceLevel = requireAllowedStringArray(
    card.experience_level,
    `cards[${index}].experience_level`,
    ALLOWED_EXPERIENCE_LEVELS,
  );

  const audience = requireAllowedStringArray(
    card.audience,
    `cards[${index}].audience`,
    ALLOWED_AUDIENCES,
  );

  const groupFamiliarity = requireAllowedStringArray(
    card.group_familiarity,
    `cards[${index}].group_familiarity`,
    ALLOWED_GROUP_FAMILIARITY,
  );

  /*
   * Lifecycle timestamps.
   *
   * The update timestamp may equal the creation timestamp but
   * may not occur earlier.
   */
  const addedAt = requireIsoTimestamp(
    card.added_to_catalog_at,
    `cards[${index}].added_to_catalog_at`,
  );

  const updatedAt = requireIsoTimestamp(
    card.updated_at,
    `cards[${index}].updated_at`,
  );

  if (updatedAt < addedAt) {
    throw new RangeError(
      `cards[${index}].updated_at cannot be earlier than added_to_catalog_at.`,
    );
  }

  /*
   * Construct the normalized trusted card record.
   *
   * Dates are serialized consistently and only validated
   * properties are retained.
   */
  return {
    card_uuid: requireString(card.card_uuid, `cards[${index}].card_uuid`, {
      maxLength: 36,
      pattern: UUID_PATTERN,
    }),

    type,

    content: {
      prompt: requireString(content.prompt, `cards[${index}].content.prompt`, {
        maxLength: LIMITS.maxPromptLength,
      }),

      instruction: optionalString(
        content.instruction,
        `cards[${index}].content.instruction`,
        {
          maxLength: LIMITS.maxInstructionLength,
        },
      ),
    },

    categories: requireStringArray(
      card.categories,
      `cards[${index}].categories`,
      {
        maxItems: LIMITS.maxCategories,
        itemPattern: ID_PATTERN,
      },
    ),

    editions: requireStringArray(card.editions, `cards[${index}].editions`, {
      maxItems: LIMITS.maxEditions,
      itemPattern: ID_PATTERN,
    }),

    visual: {
      primary_category: requireString(
        visual.primary_category,
        `cards[${index}].visual.primary_category`,
        {
          maxLength: 64,
          pattern: ID_PATTERN,
        },
      ),
    },

    response_style: responseStyle,
    answer_length: answerLength,
    experience_level: experienceLevel,
    audience,
    group_familiarity: groupFamiliarity,
    sensitivity,

    credit: {
      name: requireString(credit.name, `cards[${index}].credit.name`, {
        maxLength: LIMITS.maxDisplayNameLength,
      }),

      display: requireBoolean(credit.display, `cards[${index}].credit.display`),
    },

    source,
    status,

    active: requireBoolean(card.active, `cards[${index}].active`),

    added_to_catalog_at: addedAt.toISOString(),
    updated_at: updatedAt.toISOString(),

    content_version: requirePositiveInteger(
      card.content_version,
      `cards[${index}].content_version`,
    ),
  };
}

/* ---------------------------------------------------------
 * Catalog-wide identity checks
 * --------------------------------------------------------- */

/*
 * Require a unique value for the selected identity property
 * across an entire validated catalog.
 */
function assertUniqueIds(records, collectionName, keyName) {
  const seen = new Set();

  records.forEach((record, index) => {
    const value = record[keyName];

    if (seen.has(value)) {
      throw new Error(
        `${collectionName}[${index}].${keyName} duplicates "${value}".`,
      );
    }

    seen.add(value);
  });
}

/* ---------------------------------------------------------
 * Catalog relationship checks
 * --------------------------------------------------------- */

/*
 * Validate references between cards, categories, and
 * editions after all individual records are trusted.
 *
 * This prevents cards from referencing missing catalog
 * records or using an undeclared primary category.
 */
function validateCatalogRelationships(cards, categories, editions) {
  const categoryIds = new Set(categories.map((category) => category.id));

  const editionIds = new Set(editions.map((edition) => edition.id));

  cards.forEach((card, index) => {
    card.categories.forEach((categoryId) => {
      if (!categoryIds.has(categoryId)) {
        throw new Error(
          `cards[${index}] references unknown category "${categoryId}".`,
        );
      }
    });

    card.editions.forEach((editionId) => {
      if (!editionIds.has(editionId)) {
        throw new Error(
          `cards[${index}] references unknown edition "${editionId}".`,
        );
      }
    });

    if (!card.categories.includes(card.visual.primary_category)) {
      throw new Error(
        `cards[${index}].visual.primary_category must also appear in the card's categories array.`,
      );
    }
  });
}

/* =========================================================
 * Catalog loading
 * ========================================================= */

/*
 * Load, validate, cross-check, and store the bundled card,
 * category, and edition catalogs before the application
 * becomes interactive.
 */

/* ---------------------------------------------------------
 * JSON transport
 * --------------------------------------------------------- */

/*
 * Fetch one local JSON resource.
 *
 * Catalog requests use same-origin credentials and bypass
 * the browser cache so development changes are not masked by
 * stale data.
 */
async function fetchJson(path) {
  const response = await fetch(path, {
    credentials: "same-origin",
    cache: "no-store",
  });

  if (!response.ok) {
    throw new Error(`Unable to load ${path}: HTTP ${response.status}.`);
  }

  return response.json();
}

/* ---------------------------------------------------------
 * Catalog startup pipeline
 * --------------------------------------------------------- */

/*
 * Load all catalogs concurrently, validate every record,
 * enforce unique identities and valid relationships, then
 * populate application state and initialize the builder UI.
 */
async function loadData() {
  /*
   * Fetch all catalogs concurrently.
   */
  const [rawCards, rawCategories, rawEditions] = await Promise.all([
    fetchJson("data/cards.json"),
    fetchJson("data/categories.json"),
    fetchJson("data/editions.json"),
  ]);

  /*
   * Validate and normalize individual catalog records.
   */
  const categories = requireCatalogArray(
    rawCategories,
    "categories",
    LIMITS.maxCategories,
  ).map(validateCategory);

  /*
   * Validate and normalize individual catalog records.
   */
  const editions = requireCatalogArray(
    rawEditions,
    "editions",
    LIMITS.maxEditions,
  ).map(validateEdition);

  /*
   * Validate and normalize individual catalog records.
   */
  const cards = requireCatalogArray(rawCards, "cards", LIMITS.maxCards).map(
    validateCard,
  );

  /*
   * Enforce catalog-wide identity uniqueness.
   */
  assertUniqueIds(categories, "categories", "id");
  assertUniqueIds(editions, "editions", "id");
  assertUniqueIds(cards, "cards", "card_uuid");

  /*
   * Validate references between trusted records.
   */
  validateCatalogRelationships(cards, categories, editions);

  /*
   * Publish only fully validated catalog data.
   */
  state.cards = cards;
  state.categories = categories;
  state.editions = editions;

  /*
   * Activate the initial theme and populate the builder.
   */
  loadThemeStylesheet(state.themeId);
  renderOptions();
  renderThemeOptions();
}

/* =========================================================
 * Deck-builder controls
 * ========================================================= */

/*
 * Build and read the user controls that define which cards
 * are eligible for the next generated deck.
 */

/* ---------------------------------------------------------
 * Edition and category options
 * --------------------------------------------------------- */

/*
 * Create one safely rendered checkbox option.
 */
function createCheckboxOption({ name, value, labelText, checked }) {
  const label = document.createElement("label");
  label.className = "option";

  const input = document.createElement("input");
  input.type = "checkbox";
  input.name = name;
  input.value = value;
  input.checked = checked;

  const text = document.createElement("span");
  text.textContent = labelText;

  label.append(input, text);

  return label;
}

/*
 * Populate the active edition and category choices from the
 * validated catalogs.
 *
 * The first active edition is selected initially, while all
 * active categories are selected.
 */
function renderOptions() {
  const editionContainer = ui.editionOptions;

  const categoryContainer = ui.categoryOptions;

  editionContainer.replaceChildren();
  categoryContainer.replaceChildren();

  state.editions
    .filter((edition) => edition.active)
    .forEach((edition, index) => {
      editionContainer.appendChild(
        createCheckboxOption({
          name: "edition",
          value: edition.id,
          labelText: edition.name,
          checked: index === 0,
        }),
      );
    });

  state.categories
    .filter((category) => category.active)
    .forEach((category) => {
      categoryContainer.appendChild(
        createCheckboxOption({
          name: "category",
          value: category.id,
          labelText: `${category.icon} ${category.name}`,
          checked: true,
        }),
      );
    });
}

/* ---------------------------------------------------------
 * Theme lookup
 * --------------------------------------------------------- */

/*
 * Return a validated theme package.
 *
 * Unknown theme identifiers fail immediately rather than
 * silently falling back to another theme.
 */
function requireTheme(themeId) {
  const theme = getTheme(themeId);

  if (!validateThemeDefinition(theme)) {
    throw new Error(`Unknown or invalid theme: ${themeId}`);
  }

  return theme;
}

/*
 * Return the canonical Trail Blue fallback icon.
 *
 * This is the second stage of the application's icon
 * fallback chain:
 *
 * Theme SVG
 *     ↓
 * Trail Blue SVG
 *     ↓
 * Emoji
 */
function buildDefaultThemeIconPath(category) {
  const defaultTheme = requireTheme(DEFAULT_THEME_ID);

  return buildThemeIconPath(defaultTheme, category);
}

/* ---------------------------------------------------------
 * Theme asset resolution
 * --------------------------------------------------------- */

/*
 * Construct trusted paths to theme-owned assets.
 *
 * These helpers never concatenate arbitrary user input into
 * URLs. All paths originate from validated theme metadata.
 */

/*
 * Return the SVG icon path for one category.
 */
function buildThemeIconPath(theme, category) {
  return `${theme.assetRoot}/icons/${category.id}.svg`;
}

/*
 * Return the themed card-back artwork path.
 */
function buildThemeCardBackPath(theme) {
  return `${theme.assetRoot}/card-back.svg`;
}

/* ---------------------------------------------------------
 * Theme activation
 * --------------------------------------------------------- */

/*
 * Activate the selected theme stylesheet.
 *
 * Only one theme stylesheet is active at a time. Changing
 * themes replaces the existing stylesheet rather than
 * accumulating multiple active themes.
 */
function loadThemeStylesheet(themeId) {
  const theme = requireTheme(themeId);

  let stylesheet = document.getElementById(THEME_STYLESHEET_ID);

  if (!stylesheet) {
    stylesheet = document.createElement("link");

    stylesheet.id = THEME_STYLESHEET_ID;
    stylesheet.rel = "stylesheet";

    document.head.appendChild(stylesheet);
  }

  if (stylesheet.getAttribute("href") === theme.stylesheet) {
    return;
  }

  stylesheet.href = theme.stylesheet;
}

/* =========================================================
 * Theme subsystem
 * ========================================================= */

/*
 * Themes are trusted application packages.
 *
 * The application validates each theme definition before it
 * is used, constructs trusted asset paths beneath the theme's
 * asset root, dynamically loads the selected stylesheet, and
 * provides safe fallback behavior when optional assets are
 * unavailable.
 */

/* ---------------------------------------------------------
 * Theme definition validation
 * --------------------------------------------------------- */

/*
 * Validate one trusted theme definition exported by the
 * theme registry.
 *
 * Theme packages are application code rather than user
 * content, but validating them here produces descriptive
 * failures and keeps the contract centralized.
 */
function validateThemeDefinition(theme) {
  if (!isPlainObject(theme)) {
    return false;
  }

  return (
    typeof theme.id === "string" &&
    ID_PATTERN.test(theme.id) &&
    typeof theme.name === "string" &&
    theme.name.length > 0 &&
    theme.name.length <= LIMITS.maxDisplayNameLength &&
    typeof theme.version === "string" &&
    SEMVER_PATTERN.test(theme.version) &&
    typeof theme.author === "string" &&
    theme.author.length > 0 &&
    theme.author.length <= LIMITS.maxDisplayNameLength &&
    typeof theme.description === "string" &&
    theme.description.length > 0 &&
    theme.description.length <= 240 &&
    typeof theme.license === "string" &&
    theme.license.length > 0 &&
    theme.license.length <= 64 &&
    typeof theme.className === "string" &&
    ID_PATTERN.test(theme.className) &&
    theme.className === `theme-${theme.id}` &&
    typeof theme.stylesheet === "string" &&
    theme.stylesheet === `themes/${theme.id}/theme.css` &&
    theme.stylesheet.length > 0 &&
    theme.stylesheet.length <= 200 &&
    theme.stylesheet.startsWith("themes/") &&
    theme.stylesheet.endsWith("/theme.css") &&
    !theme.stylesheet.includes("..") &&
    !theme.stylesheet.includes("\\") &&
    !theme.stylesheet.includes(":") &&
    !theme.stylesheet.startsWith("/") &&
    typeof theme.assetRoot === "string" &&
    typeof theme.assetRoot === "string" &&
    theme.assetRoot === `themes/${theme.id}/assets` &&
    theme.assetRoot.length > 0 &&
    theme.assetRoot.length <= 200 &&
    theme.assetRoot.startsWith("themes/") &&
    theme.assetRoot.endsWith("/assets") &&
    !theme.assetRoot.includes("..") &&
    !theme.assetRoot.includes("\\") &&
    !theme.assetRoot.includes(":") &&
    !theme.assetRoot.startsWith("/")
  );
}

/* ---------------------------------------------------------
 * Theme selector
 * --------------------------------------------------------- */

/*
 * Populate the Theme picker using the validated registry.
 */
function renderThemeOptions() {
  const selector = ui.themeSelect;

  selector.replaceChildren();

  themes.forEach((theme) => {
    if (!validateThemeDefinition(theme)) {
      throw new Error(
        "The trusted theme registry contains an invalid theme definition.",
      );
    }

    const option = document.createElement("option");
    option.value = theme.id;
    option.textContent = theme.name;

    selector.appendChild(option);
  });

  const selectedTheme = getTheme(state.themeId);

  if (!validateThemeDefinition(selectedTheme)) {
    throw new Error(`Unknown or invalid initial theme: ${state.themeId}`);
  }

  selector.value = selectedTheme.id;
}

/*
 * Return the selected checkbox values for one builder option
 * group.
 *
 * Restricting accepted group names prevents arbitrary CSS
 * selectors from being constructed from caller input.
 */
function getSelectedOptionValues(name) {
  if (name !== "edition" && name !== "category") {
    throw new Error(`Unsupported option group requested: ${name}`);
  }

  const selected = [
    ...document.querySelectorAll(`input[name="${name}"]:checked`),
  ].map((input) => input.value);

  const records = name === "edition" ? state.editions : state.categories;

  const allowedIds = new Set(
    records.filter((record) => record.active).map((record) => record.id),
  );

  selected.forEach((value) => {
    if (!allowedIds.has(value)) {
      throw new Error(`Unsupported ${name} selection: ${value}`);
    }
  });

  return selected;
}

/* ---------------------------------------------------------
 * Generation input validation
 * --------------------------------------------------------- */

/*
 * Require a whole-number playable-card count within the
 * application limit.
 */
function validateDeckSize(rawValue) {
  const size = Number(rawValue);

  if (!Number.isInteger(size)) {
    throw new TypeError("Deck size must be a whole number.");
  }

  if (size < 1 || size > LIMITS.maxDeckSize) {
    throw new RangeError(
      `Deck size must be between 1 and ${LIMITS.maxDeckSize}.`,
    );
  }

  return size;
}

/*
 * Normalize the generation seed.
 *
 * An empty value falls back to the demonstration seed so
 * generation remains deterministic.
 */
function validateSeed(rawSeed) {
  const normalized = typeof rawSeed === "string" ? rawSeed.trim() : "";

  const seed = normalized || "trailtalk-demo";

  if (seed.length > LIMITS.maxSeedLength) {
    throw new RangeError(
      `Seed cannot exceed ${LIMITS.maxSeedLength} characters.`,
    );
  }

  return seed;
}

/* =========================================================
 * Deck generation
 * ========================================================= */

/*
 * Convert the current builder configuration and validated
 * catalog into a reproducible, permanently positioned deck
 * and its downloadable manifest.
 */

/* ---------------------------------------------------------
 * Generated-state reset
 * --------------------------------------------------------- */

/*
 * Discard the current generated deck, manifest, preview, and
 * print output.
 */
function clearGeneratedOutput() {
  state.generated = [];
  state.manifest = null;

  ui.previewOutput.replaceChildren();
  ui.printOutput.replaceChildren();
}

/* ---------------------------------------------------------
 * Deterministic deck identity
 * --------------------------------------------------------- */

/*
 * Create the canonical fingerprint and human-readable Deck ID
 * for a generated playable deck.
 *
 * Set-like configuration arrays are sorted, while card order
 * is preserved because permanent deck position is meaningful.
 */
async function createDeckIdentity({
  seed,
  editions,
  categories,
  requestedCardCount,
  cards,
}) {
  const identityPayload = {
    identity_version: DECK_IDENTITY_VERSION,
    generator_version: GENERATOR_VERSION,
    catalog_version: CATALOG_VERSION,
    seed,
    editions: [...editions].sort(),
    categories: [...categories].sort(),
    requested_card_count: requestedCardCount,

    /*
     * Ordered card identities make the fingerprint
     * describe the actual playable deck.
     */
    cards: cards.map((card) => ({
      card_uuid: card.card_uuid,
      content_version: card.content_version,
    })),
  };

  /*
   * Property order is intentionally fixed above, and
   * set-like arrays are sorted before serialization.
   */
  const canonicalPayload = JSON.stringify(identityPayload);

  const digest = await sha256Bytes(canonicalPayload);

  const fingerprint = bytesToHex(digest);

  const deckId = encodeBase32(digest).slice(0, HUMAN_DECK_ID_LENGTH);

  /*
   * Return both machine-readable and human-readable identities.
   */
  return {
    deckId,
    fingerprint,
    identityPayload,
  };
}

/*
 * Return true when a card is playable for the selected
 * editions and categories.
 *
 * A playable card must be active, approved, and associated
 * with at least one selected edition and one selected
 * category.
 */
function cardMatchesSelection(card, editions, categories) {
  return (
    card.active &&
    card.status === "approved" &&
    card.editions.some((editionId) => editions.includes(editionId)) &&
    card.categories.some((categoryId) => categories.includes(categoryId))
  );
}

/*
 * Build the manifest describing one generated deck.
 *
 * This preserves the generation configuration, deterministic
 * identity fields, and immutable card-content snapshots used
 * to identify or reproduce the deck.
 */
function buildManifest({
  deckUuid,
  deckId,
  fingerprint,
  seed,
  editions,
  categories,
  requested,
  generated,
}) {
  return {
    deck_uuid: deckUuid,
    deck_id: deckId,
    deck_fingerprint: fingerprint,
    deck_identity_version: DECK_IDENTITY_VERSION,

    generated_at: new Date().toISOString(),

    seed,

    generator_version: GENERATOR_VERSION,

    catalog_version: CATALOG_VERSION,

    configuration: {
      editions: [...editions],
      categories: [...categories],
      theme: state.themeId,
      requested_card_count: requested,
      playable_card_count: generated.length,
    },

    cards: generated.map((card) => ({
      deck_position: card.deck_position,

      card_uuid: card.card_uuid,

      content_version: card.content_version,

      content_snapshot: {
        prompt: card.content.prompt,

        instruction: card.content.instruction,
      },
    })),
  };
}

/*
 * Return a copy of the generated deck with permanent
 * one-based positions assigned.
 *
 * These positions become part of the deck identity and
 * remain stable for this generated deck.
 */
function assignDeckPositions(cards) {
  return cards.map((card, index) => ({
    deck_position: index + 1,
    ...card,
  }));
}

/*
 * Generate a secure UUID for one manifest instance.
 *
 * The deterministic Deck ID identifies the generated deck
 * configuration and card order. This UUID uniquely identifies
 * this particular generation event and downloaded manifest.
 */
function createDeckUuid() {
  if (
    !globalThis.crypto ||
    typeof globalThis.crypto.randomUUID !== "function"
  ) {
    throw new Error(
      "Secure UUID generation is not available in this browser context.",
    );
  }

  return globalThis.crypto.randomUUID();
}

/* ---------------------------------------------------------
 * Generation transaction
 * --------------------------------------------------------- */

/*
 * Generate one playable deck from the current builder state.
 *
 * The operation either completes with a matching generated
 * deck and manifest or reports a failure without exposing
 * partially generated output.
 */
async function generateDeck() {
  /*
   * Read and validate the requested configuration.
   */
  try {
    const editions = getSelectedOptionValues("edition");
    const categories = getSelectedOptionValues("category");

    const requested = validateDeckSize(ui.deckSizeInput.value);

    const seed = validateSeed(ui.seedInput.value);

    /*
     * Require at least one edition and one category.
     */
    if (editions.length === 0 || categories.length === 0) {
      setStatus("Select at least one edition and one category.");

      return;
    }

    /*
     * Find active, approved cards matching both the selected
     * edition set and category set.
     */
    const eligible = state.cards.filter((card) =>
      cardMatchesSelection(card, editions, categories),
    );

    /*
     * Clear stale output when the current configuration has no
     * playable cards.
     */
    if (eligible.length === 0) {
      clearGeneratedOutput();

      setStatus("No cards match the selected editions and categories.");

      return;
    }

    /*
     * Select cards deterministically without mutating the
     * validated catalog order.
     */
    const chosen = seededShuffle(eligible, seed).slice(
      0,
      Math.min(requested, eligible.length),
    );

    /*
     * Assign a unique manifest-instance UUID in addition to the
     * deterministic Deck ID and fingerprint.
     */
    const deckUuid = createDeckUuid();

    const { deckId, fingerprint } = await createDeckIdentity({
      seed,
      editions,
      categories,
      requestedCardCount: requested,
      cards: chosen,
    });

    /*
     * Preserve permanent one-based positions for this generated
     * deck.
     */
    state.generated = assignDeckPositions(chosen);

    /*
     * Capture the generation configuration and immutable card
     * content snapshots needed to identify or reproduce the deck.
     */
    state.manifest = buildManifest({
      deckUuid,
      deckId,
      fingerprint,
      seed,
      editions,
      categories,
      requested,
      generated: state.generated,
    });

    /*
     * Report whether the requested deck size was fully satisfied.
     */
    setStatus(
      chosen.length < requested
        ? `Only ${chosen.length} eligible cards were available.`
        : `Generated ${chosen.length} playable cards.`,
    );

    /*
     * Render preview and print output from the same generated
     * deck state.
     */
    renderOutput();
  } catch (error) {
    /*
     * Fail visibly without exposing an uncaught generation error
     * to the user.
     */
    console.error(error);

    setStatus(
      error instanceof Error
        ? error.message
        : "The deck could not be generated.",
    );
  }
}

/* =========================================================
 * Shared rendering resources
 * ========================================================= */

/*
 * Resolve validated catalog relationships and create
 * theme-aware decorative assets shared by preview, print,
 * and Quick List output.
 */

/* ---------------------------------------------------------
 * Primary-category lookup
 * --------------------------------------------------------- */

/*
 * Return the validated primary category for one card.
 *
 * Catalog relationship validation should guarantee that the
 * category exists. This defensive check protects rendering if
 * application state is ever modified incorrectly.
 */
function categoryFor(card) {
  const category = state.categories.find(
    (candidate) => candidate.id === card.visual.primary_category,
  );

  if (!category) {
    throw new Error(
      `Card ${card.card_uuid} references a missing primary category.`,
    );
  }

  return category;
}

/* ---------------------------------------------------------
 * Category artwork
 * --------------------------------------------------------- */

/*
 * Create a category icon with graceful fallback behavior.
 *
 * Fallback order:
 *
 * 1. Selected theme SVG
 * 2. Trail Blue canonical SVG
 * 3. Catalog emoji
 *
 * The wrapper may be decorative or may expose the category
 * name to assistive technology, depending on its use.
 */
function createCategoryIcon(
  category,
  { className = "", decorative = true, themeId = state.themeId } = {},
) {
  /*
   * Resolve the requested trusted theme.
   */
  const theme = requireTheme(themeId);

  /*
   * Create the semantic icon container.
   */
  const wrapper = document.createElement("span");

  if (className) {
    wrapper.className = className;
  }

  if (decorative) {
    wrapper.setAttribute("aria-hidden", "true");
  } else {
    wrapper.setAttribute("aria-label", category.name);
  }

  /*
   * Attempt the selected theme asset first.
   */
  const image = document.createElement("img");

  image.src = buildThemeIconPath(theme, category);

  image.alt = "";

  image.width = 32;
  image.height = 32;

  image.className = "category-svg-icon";

  /*
   * Fall through to Trail Blue, then to the catalog emoji.
   */
  image.onerror = () => {
    if (theme.id === DEFAULT_THEME_ID) {
      wrapper.textContent = category.icon;
      return;
    }

    image.onerror = () => {
      wrapper.textContent = category.icon;
    };

    image.src = buildDefaultThemeIconPath(category);
  };

  wrapper.appendChild(image);

  return wrapper;
}

/* ---------------------------------------------------------
 * Card-back artwork
 * --------------------------------------------------------- */

/*
 * Create the optional decorative card-back graphic.
 *
 * Fallback order:
 *
 * 1. Selected theme card-back.svg
 * 2. Trail Blue canonical card-back.svg
 * 3. No graphic; preserve the complete text-only card back
 */
function createCardBackGraphic({ themeId = state.themeId } = {}) {
  const theme = requireTheme(themeId);

  const wrapper = document.createElement("div");

  wrapper.className = "card-back-main-graphic";

  /*
   * The image is decorative. The meaningful content
   * of the card back remains available as text.
   */
  wrapper.setAttribute("aria-hidden", "true");

  const image = document.createElement("img");

  image.className = "card-back-main-graphic-image";

  image.alt = "";

  image.src = buildThemeCardBackPath(theme);

  image.onerror = () => {
    /*
     * Trail Blue is the canonical fallback theme.
     * Do not request the same missing asset twice.
     */
    if (theme.id === DEFAULT_THEME_ID) {
      wrapper.remove();
      return;
    }

    const defaultTheme = requireTheme(DEFAULT_THEME_ID);

    image.onerror = () => {
      /*
       * Both assets are unavailable. Remove the
       * decorative graphic and retain the complete
       * text-only card back.
       */
      wrapper.remove();
    };

    image.src = buildThemeCardBackPath(defaultTheme);
  };

  wrapper.appendChild(image);

  return wrapper;
}

/* =========================================================
 * Canonical card renderers
 * ========================================================= */

/*
 * These functions create the physical card faces shared by
 * both interactive preview output and printable output.
 *
 * They render from the same generated deck state so preview
 * and print remain synchronized.
 */

/* ---------------------------------------------------------
 * Card front
 * --------------------------------------------------------- */

/*
 * Render one complete card front:
 *
 * - category banner
 * - banner icon and name
 * - center icon
 * - prompt
 * - optional instruction
 * - permanent Deck ID and position footer
 */
function renderFrontCard(card, { themeId = state.themeId } = {}) {
  /*
   * Resolve the card's primary category and requested theme.
   */
  const category = categoryFor(card);
  const theme = requireTheme(themeId);

  /*
   * Create the physical card container.
   */
  const article = document.createElement("article");

  article.classList.add("play-card", "card-front", theme.className);

  /*
   * Build the category banner.
   */
  const band = document.createElement("div");

  band.classList.add("card-band", `category-${category.id}`);

  const bandIcon = createCategoryIcon(category, {
    className: "category-icon",
  });

  const bandName = document.createElement("span");

  bandName.className = "category-name";
  bandName.textContent = category.name;

  band.append(bandIcon, bandName);

  /*
   * Build the centered prompt content.
   */
  const body = document.createElement("div");
  body.className = "card-body";

  const bodyContent = document.createElement("div");

  const cardIcon = createCategoryIcon(category, {
    className: "card-icon",
  });

  const prompt = document.createElement("p");
  prompt.className = "card-prompt";
  prompt.textContent = card.content.prompt;

  bodyContent.append(cardIcon, prompt);

  /*
   * Add optional play guidance only when present.
   */
  if (card.content.instruction) {
    const instruction = document.createElement("p");

    instruction.className = "card-instruction";

    instruction.textContent = card.content.instruction;

    bodyContent.appendChild(instruction);
  }

  body.appendChild(bodyContent);

  /*
   * Add the deterministic Deck ID and permanent position.
   */
  const footer = document.createElement("div");

  footer.className = "card-footer";

  const footerText = document.createElement("span");

  footerText.textContent =
    `${state.manifest.deck_id} · ` +
    `${card.deck_position}/` +
    `${state.generated.length}`;

  footer.appendChild(footerText);

  article.append(band, body, footer);

  return article;
}

/* ---------------------------------------------------------
 * Card back
 * --------------------------------------------------------- */

/*
 * Render one complete card back:
 *
 * - optional hole-punch guide
 * - theme-owned decorative artwork
 * - application-owned title
 * - theme-styled divider
 * - application-owned tagline
 * - application-owned brand
 */
function renderBackCard({
  showPunchGuide = true,
  themeId = state.themeId,
} = {}) {
  const theme = requireTheme(themeId);

  /*
   * Create the theme-styled divider as a standalone element.
   */
  const divider = document.createElement("div");

  divider.className = "card-back-divider";

  divider.setAttribute("aria-hidden", "true");

  /*
   * Create the physical card container.
   */
  const article = document.createElement("article");

  article.classList.add("play-card", "card-back", theme.className);

  /*
   * Add the application-owned hole-punch guide when requested.
   */
  if (showPunchGuide) {
    const punchGuide = document.createElement("div");

    punchGuide.className = "punch-safe punch-safe-back";

    punchGuide.title = "Optional hole-punch safe area";

    article.appendChild(punchGuide);
  }

  /*
   * Build the semantic card-back content stack.
   */
  const content = document.createElement("div");

  content.className = "card-back-content";

  /*
   * Add optional theme artwork with graceful fallback.
   */
  const mainGraphic = createCardBackGraphic({
    themeId,
  });

  /*
   * Add canonical application identity text.
   */
  const heading = document.createElement("h3");

  heading.className = "card-back-title";

  heading.textContent = APP_IDENTITY.title;

  const tagline = document.createElement("p");

  tagline.className = "card-back-tagline";

  const taglineLineOne = document.createElement("span");

  taglineLineOne.textContent =
    APP_IDENTITY.taglineLineOne + " " + APP_IDENTITY.taglineLineTwo;

  const taglineLineTwo = document.createElement("span");

  taglineLineTwo.textContent = ""; //APP_IDENTITY.taglineLineTwo;

  tagline.append(taglineLineOne, taglineLineTwo);

  const brand = document.createElement("p");

  brand.className = "card-back-brand";

  brand.textContent = APP_IDENTITY.brand;

  content.append(mainGraphic, heading, divider, tagline, brand);

  article.appendChild(content);

  return article;
}

/*
 * Render one interactive preview card.
 *
 * Preview cards reuse the canonical front and back renderers
 * so the preview always matches printed output.
 */
function renderPreviewCard(card) {
  /*
   * Create the interactive preview container.
   */
  const wrapper = document.createElement("div");

  wrapper.className = "preview-card";
  wrapper.setAttribute("role", "button");
  wrapper.tabIndex = 0;

  wrapper.setAttribute("aria-pressed", "false");

  wrapper.setAttribute(
    "aria-label",
    `Flip card ${card.deck_position} to view the back`,
  );

  const inner = document.createElement("div");

  inner.className = "preview-card-inner";

  const frontSide = document.createElement("div");

  frontSide.className = "preview-card-side preview-card-front";

  /*
   * Build the canonical front card face.
   */
  frontSide.appendChild(renderFrontCard(card));

  const backSide = document.createElement("div");

  backSide.className = "preview-card-side preview-card-back";

  /*
   * Build the canonical back card face.
   */
  backSide.appendChild(
    renderBackCard({
      showPunchGuide: true,
    }),
  );

  inner.append(frontSide, backSide);
  wrapper.appendChild(inner);

  return wrapper;
}

/* =========================================================
 * Output coordination
 * ========================================================= */

/*
 * Render every presentation of the generated deck from the
 * same application state.
 *
 * Preview and printable output are always regenerated
 * together.
 */
function renderOutput() {
  renderPreview();
  renderPrintOutput();
}

/*
 * Render the summary panel shown above the preview.
 *
 * The panel reports the generated deck identity and the
 * configuration used to create it.
 */
function renderPreviewStatus() {
  if (!state.manifest) {
    return null;
  }

  const configuration = state.manifest.configuration;

  const theme = getTheme(state.themeId);

  if (!validateThemeDefinition(theme)) {
    throw new Error(`Unknown or invalid theme: ${state.themeId}`);
  }

  const editionNames = configuration.editions
    .map((editionId) =>
      state.editions.find((edition) => edition.id === editionId),
    )
    .filter(Boolean)
    .map((edition) => edition.name);

  const categoryNames = configuration.categories
    .map((categoryId) =>
      state.categories.find((category) => category.id === categoryId),
    )
    .filter(Boolean)
    .map((category) => category.name);

  const header = document.createElement("header");

  header.className = "preview-status";

  const headingRow = document.createElement("div");

  headingRow.className = "preview-status-heading";

  const headingText = document.createElement("div");

  const eyebrow = document.createElement("p");

  eyebrow.className = "preview-status-eyebrow";

  eyebrow.textContent = "Deck Preview";

  const heading = document.createElement("h2");

  heading.textContent = `Deck ${state.manifest.deck_id}`;

  headingText.append(eyebrow, heading);

  const count = document.createElement("span");

  count.className = "preview-status-count";

  count.textContent = `${state.generated.length} cards`;

  headingRow.append(headingText, count);

  const details = document.createElement("dl");

  details.className = "preview-status-details";

  details.append(
    createStatusDetail("Theme", theme.name),

    createStatusDetail("Editions", editionNames.join(", ")),

    createStatusDetail("Categories", categoryNames.join(", ")),

    createStatusDetail("Seed", state.manifest.seed, {
      useCode: true,
    }),
  );

  header.append(headingRow, details);

  return header;
}

/* =========================================================
 * Interactive preview
 * ========================================================= */

/*
 * The screen preview is a complete interactive view of the
 * generated deck.
 *
 * Unlike printable output, preview cards can be flipped to
 * inspect both sides before printing.
 */

/* ---------------------------------------------------------
 * Preview status panel
 * --------------------------------------------------------- */

/*
 * Create one labeled value displayed in the preview summary.
 */
function createStatusDetail(label, value, { useCode = false } = {}) {
  const wrapper = document.createElement("div");

  const term = document.createElement("dt");

  term.textContent = label;

  const description = document.createElement("dd");

  if (useCode) {
    const code = document.createElement("code");

    code.textContent = value;
    description.appendChild(code);
  } else {
    description.textContent = value;
  }

  wrapper.append(term, description);

  return wrapper;
}

/* ---------------------------------------------------------
 * Preview coordinator
 * --------------------------------------------------------- */

/*
 * Render the complete interactive preview.
 *
 * This function owns only preview composition. Individual
 * cards and status details are delegated to helper
 * functions.
 */
function renderPreview() {
  const mode = ui.outputMode.value;

  const output = ui.previewOutput;

  output.replaceChildren();

  const status = renderPreviewStatus();

  if (status) {
    output.appendChild(status);
  }

  if (mode === "list") {
    renderQuickList(output);

    return;
  }

  const previewGrid = document.createElement("div");

  previewGrid.className = "card-grid preview-card-grid";

  state.generated.forEach((card) => {
    previewGrid.appendChild(renderPreviewCard(card));
  });

  output.appendChild(previewGrid);

  previewGrid.querySelectorAll(".preview-card").forEach((cardElement) => {
    cardElement.addEventListener("click", () => {
      togglePreviewCard(cardElement);
    });

    cardElement.addEventListener("keydown", (event) => {
      if (event.key === "Enter" || event.key === " ") {
        event.preventDefault();

        togglePreviewCard(cardElement);
      }
    });
  });
}

/* ---------------------------------------------------------
 * Preview interaction
 * --------------------------------------------------------- */

/*
 * Flip one preview card between its front and back faces.
 */
function togglePreviewCard(cardElement) {
  const isFlipped = cardElement.classList.toggle("is-flipped");

  cardElement.setAttribute("aria-pressed", String(isFlipped));

  cardElement.setAttribute(
    "aria-label",
    isFlipped ? "Flip card to view the front" : "Flip card to view the back",
  );
}

/* =========================================================
 * Quick List
 * ========================================================= */

/*
 * Render a compact printable reference list.
 *
 * The Quick List preserves permanent Deck IDs and positions
 * while minimizing paper usage for last-minute trips.
 */
function renderQuickList(container) {
  const list = document.createElement("div");

  list.className = "quick-list";

  /*
   * Populate the supplied Quick List container.
   */
  state.generated.forEach((card) => {
    const category = categoryFor(card);

    const article = document.createElement("article");

    article.className = "list-item";

    const metadata = document.createElement("div");

    metadata.className = "list-meta";

    metadata.append(
      document.createTextNode(
        `${state.manifest.deck_id} · ` +
          `${card.deck_position}/` +
          `${state.generated.length}`,
      ),
      document.createElement("br"),
      createCategoryIcon(category, {
        className: "list-category-icon",
      }),
      document.createTextNode(` ${category.name}`),
    );

    const prompt = document.createElement("p");

    prompt.className = "list-prompt";

    const strong = document.createElement("strong");

    strong.textContent = card.content.prompt;

    prompt.appendChild(strong);

    if (card.content.instruction) {
      prompt.append(
        document.createElement("br"),
        document.createTextNode(card.content.instruction),
      );
    }

    article.append(metadata, prompt);
    list.appendChild(article);
  });

  container.appendChild(list);
}

/* =========================================================
 * Printable output
 * ========================================================= */

/*
 * Render duplex-ready pages.
 *
 * Front pages are immediately followed by their matching
 * back pages to support long-edge duplex printing.
 */
function renderPrintOutput() {
  const mode = ui.outputMode.value;

  const output = ui.printOutput;

  output.replaceChildren();

  /*
   * Quick List mode bypasses card rendering entirely.
   */
  if (mode === "list") {
    renderQuickList(output);

    return;
  }

  const cardsPerPage = 6;

  /*
   * Group cards into printable six-card sheets.
   */
  const cardGroups = chunkArray(state.generated, cardsPerPage);

  cardGroups.forEach((cards) => {
    const firstPosition = cards[0].deck_position;

    const lastPosition = cards[cards.length - 1].deck_position;

    /*
     * Create the front page for this sheet.
     */
    const frontPage = document.createElement("section");

    frontPage.className = "print-page front-page";

    frontPage.dataset.pageType = "front";

    frontPage.dataset.cardRange = `${firstPosition}-${lastPosition}`;

    const frontGrid = document.createElement("div");

    frontGrid.className = "card-grid";

    cards.forEach((card) => {
      frontGrid.appendChild(renderFrontCard(card));
    });

    frontPage.appendChild(frontGrid);
    output.appendChild(frontPage);

    /*
     * Create the matching back page.
     */
    const backPage = document.createElement("section");

    backPage.className = "print-page back-page";

    backPage.dataset.pageType = "back";

    backPage.dataset.cardRange = `${firstPosition}-${lastPosition}`;

    const backGrid = document.createElement("div");

    backGrid.className = "card-grid";

    cards.forEach(() => {
      backGrid.appendChild(renderBackCard());
    });

    backPage.appendChild(backGrid);
    output.appendChild(backPage);
  });
}

/* =========================================================
 * Manifest export
 * ========================================================= */

/*
 * Download the generated deck manifest.
 *
 * The manifest contains the information required to identify
 * or reproduce the generated deck independently of the
 * printed cards.
 */
function downloadManifest() {
  if (!state.manifest) {
    setStatus("Generate a deck first.");

    return;
  }

  const blob = new Blob([JSON.stringify(state.manifest, null, 2)], {
    type: "application/json",
  });

  const url = URL.createObjectURL(blob);

  const anchor = document.createElement("a");

  anchor.href = url;

  anchor.download = `trailtalk-${state.manifest.deck_id}` + "-manifest.json";

  anchor.hidden = true;

  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();

  window.setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 0);
}

/* =========================================================
 * Application lifecycle
 * ========================================================= */

/*
 * Register user interactions and perform application
 * startup.
 *
 * Initialization order:
 *
 *   1. Register event handlers.
 *   2. Load and validate catalogs.
 *   3. Activate the default theme.
 *   4. Render the initial builder.
 */

/* =========================================================
 * Event handlers
 * ========================================================= */

/*
 * Generate a new secure, human-readable seed and place it
 * into the builder control.
 */
function handleRandomSeed() {
  ui.seedInput.value = randomCode(RANDOM_SEED_LENGTH);
}

/*
 * Open the browser's print dialog.
 */
function handlePrint() {
  window.print();
}

/*
 * Download the current generated-deck manifest.
 */
function handleManifestDownload() {
  downloadManifest();
}

/*
 * Re-render an existing generated deck when the user changes
 * between Poker Cards and Quick List modes.
 */
function handleOutputModeChange() {
  if (state.generated.length > 0) {
    renderOutput();
  }
}

/*
 * Activate the selected theme and re-render existing output.
 *
 * A rejected theme selection restores the previously active
 * theme without modifying generated deck state.
 */
function handleThemeChange(event) {
  const requestedThemeId = event.target.value;

  try {
    const selectedTheme = requireTheme(requestedThemeId);

    state.themeId = selectedTheme.id;

    loadThemeStylesheet(state.themeId);

    if (state.manifest) {
      state.manifest.configuration.theme = state.themeId;
    }

    if (state.generated.length > 0) {
      renderOutput();
    }
  } catch (error) {
    console.error(error);

    setStatus("The selected theme is not available.");

    event.target.value = state.themeId;
  }
}

/* =========================================================
 * Event registration
 * ========================================================= */

/*
 * Connect page controls to their application handlers.
 */
function registerEventListeners() {
  ui.generateButton.addEventListener("click", generateDeck);

  ui.randomSeedButton.addEventListener("click", handleRandomSeed);

  ui.printButton.addEventListener("click", handlePrint);

  ui.manifestButton.addEventListener("click", handleManifestDownload);

  ui.outputMode.addEventListener("change", handleOutputModeChange);

  ui.themeSelect.addEventListener("change", handleThemeChange);
}

registerEventListeners();

loadData().catch((error) => {
  console.error(error);

  clearGeneratedOutput();

  setStatus(
    "The card catalog could not be loaded safely. " +
      "Check the browser console for details.",
  );
});
